-- | Core Pattern data type and basic operations.
--
-- This module defines the fundamental Pattern type as a recursive structure
-- that can represent graph elements and sequences.
--
-- == Conceptual Model: Patterns as Decorated Sequences
--
-- Conceptually, a Pattern is a decorated sequence: the elements form the pattern
-- itself, and the value provides decoration (metadata) about that pattern.
-- For example, the pattern "A B B A" with decoration "Enclosed rhyme" represents
-- a specific sequence pattern (A B B A) that is classified as an "Enclosed rhyme".
-- The Pattern type represents such decorated sequences where:
--
-- * @elements@ - The pattern itself, represented as a sequence of elements
-- * @value@ - Decoration or metadata about what kind of pattern it is
--
-- The elements ARE the pattern; they are not children or subordinate to the value.
-- While implemented using a recursive tree structure, the primary semantic is that
-- elements form the pattern sequence itself. Each element in the sequence is itself
-- a Pattern, enabling arbitrarily nested and complex pattern structures.
--
-- == Implementation: Recursive Structure
--
-- The Pattern type is implemented as a recursive tree structure, but this is purely
-- an implementation detail. Conceptually:
--
-- * Each pattern's @elements@ field IS the pattern - it contains the sequence that defines the pattern
-- * Each pattern's @value@ field provides decoration about what kind of pattern it is
-- * The recursive structure enables patterns to contain patterns containing patterns, etc.
--
-- This recursive implementation enables:
--
-- * Empty patterns: Patterns with no elements (@elements == []@), representing empty sequences
-- * Patterns with elements: Patterns containing one or more pattern elements in sequence
-- * Arbitrary nesting: Patterns can contain patterns containing patterns, enabling
--   deeply nested pattern structures
--
-- == Values and Pattern Decoration
--
-- Each Pattern instance decorates a sequence of elements with metadata:
--
-- * The @value@ field stores decoration about what kind of pattern it is. This can be any type @v@,
--   such as a string identifier, an integer, a custom data type, etc.
-- * The @value@ is decoration about the pattern sequence itself, not part of the pattern.
-- * All patterns in a structure must share the same value type @v@ (enforced by the type system).
--
-- For example, a pattern representing a graph node might have @value = "Person"@
-- (decoration indicating the node type) and @elements = []@ (empty sequence pattern).
-- A pattern representing a relationship might have @value = "knows"@ (the relationship type decoration)
-- and @elements = [nodeA, nodeB]@ (the pattern itself - a sequence of two node patterns).
--
-- == Elements and Pattern Structure
--
-- The @elements@ field IS the pattern - it contains the sequence that defines the pattern:
--
-- * An empty sequence (@elements == []@) represents a pattern with no elements (empty sequence)
-- * A non-empty sequence represents a pattern containing one or more pattern elements
-- * The elements are ordered and maintain their sequence order - this order is essential to the pattern
-- * Each element in the sequence is itself a Pattern, enabling recursive nesting
--
-- The pattern structure enables compositional patterns:
--
-- * A pattern can include other patterns as its elements
-- * Those element patterns can themselves include patterns
-- * This enables arbitrary depth nesting while maintaining the pattern sequence semantic
--
-- For example, a graph pattern might have @elements = [node1, node2, relationship1]@
-- where each element is a Pattern. The relationship pattern itself might have
-- @elements = [nodeA, nodeB]@, creating a nested pattern structure.
--
-- == Type Safety and Type Parameter @v@
--
-- The Pattern type is parameterized over value type @v@:
--
-- * @Pattern v@ allows patterns to store values of any type @v@
-- * All patterns in a structure must share the same value type @v@
-- * This type consistency is enforced by Haskell's type system
-- * The type parameter ensures type safety when working with patterns
--
-- For example:
--
-- * @Pattern String@ - patterns storing string values
-- * @Pattern Int@ - patterns storing integer values
-- * @Pattern Person@ - patterns storing custom Person values
--
-- Type consistency means that if you have a @Pattern String@, all patterns in
-- its @elements@ list must also be @Pattern String@. This prevents mixing
-- different value types within a single pattern structure.
--
-- == Mathematical Foundation
--
-- Patterns form the foundation for category-theoretic graph representations.
-- The recursive structure enables functor instances (to be added in future phases)
-- and supports various graph interpretations through categorical views. The sequence
-- semantic aligns with categorical composition and transformation operations.
--
-- == Examples
--
-- Empty pattern (node):
--
-- >>> leaf = Pattern { value = "node1", elements = [] }
-- >>> value leaf
-- "node1"
-- >>> elements leaf
-- []
--
-- Pattern with elements:
--
-- >>> elem1 = Pattern { value = "elem1", elements = [] }
-- >>> elem2 = Pattern { value = "elem2", elements = [] }
-- >>> pattern = Pattern { value = "pattern", elements = [elem1, elem2] }
-- >>> value pattern
-- "pattern"
-- >>> length (elements pattern)
-- 2
-- >>> map value (elements pattern)
-- ["elem1","elem2"]
--
-- Nested patterns (arbitrary depth):
--
-- >>> level3 = Pattern { value = "level3", elements = [] }
-- >>> level2 = Pattern { value = "level2", elements = [level3] }
-- >>> level1 = Pattern { value = "level1", elements = [level2] }
-- >>> nested = Pattern { value = "root", elements = [level1] }
-- >>> value nested
-- "root"
-- >>> value (head (elements nested))
-- "level1"
--
-- Empty patterns with different value types:
--
-- >>> leafString = Pattern { value = "text", elements = [] }
-- >>> leafInt = Pattern { value = 42, elements = [] }
-- >>> value leafString
-- "text"
-- >>> value leafInt
-- 42
--
-- Patterns with varying numbers of elements:
--
-- >>> zeroElements = Pattern { value = "zero", elements = [] }
-- >>> oneElement = Pattern { value = "one", elements = [Pattern { value = "elem", elements = [] }] }
-- >>> manyElements = Pattern { value = "many", elements = [Pattern { value = "e1", elements = [] }, Pattern { value = "e2", elements = [] }] }
-- >>> length (elements zeroElements)
-- 0
-- >>> length (elements oneElement)
-- 1
-- >>> length (elements manyElements)
-- 2
module Pattern.Core where

-- | A recursive structure representing a decorated sequence pattern.
--
-- Conceptually, a Pattern is a decorated sequence: the elements form the pattern
-- itself, and the value provides decoration (metadata) about that pattern.
-- For example, the pattern "A B B A" with decoration "Enclosed rhyme" represents
-- a specific sequence pattern (A B B A) that is classified as an "Enclosed rhyme".
-- The Pattern type represents such decorated sequences where each element is itself
-- a Pattern, enabling recursive nesting.
--
-- Patterns form the foundation for representing graph elements and sequences.
-- Each pattern decorates a sequence of pattern elements with a value of any type.
-- The recursive structure enables compositional and nested patterns while maintaining
-- the decorated sequence semantic.
--
-- The Pattern type is intentionally minimal - it provides just the structure
-- needed for recursive sequence representation. Classification functions
-- (identifying nodes, relationships, subgraphs) will be added in future phases.
--
-- === Type Parameter @v@
--
-- The @v@ type parameter allows patterns to store decorations of any type.
-- All patterns in a structure must share the same value type @v@. This type
-- consistency is enforced by Haskell's type system, ensuring type safety when
-- working with patterns.
--
-- For example, @Pattern String@ represents patterns with string decorations,
-- @Pattern Int@ represents patterns with integer decorations, and @Pattern Person@
-- represents patterns with custom Person decorations. All elements in a pattern's
-- sequence must have the same decoration type as the pattern itself.
--
-- === Pattern Variants
--
-- * Empty pattern: @elements == []@ - a sequence with no elements, representing
--   a simple entity or atomic pattern
-- * Pattern with elements: @elements@ contains one or more pattern elements -
--   represents relationships, subgraphs, or complex sequence structures
--
-- === Examples
--
-- Creating an empty pattern (node):
--
-- >>> nodeA = Pattern { value = "A", elements = [] }
--
-- Creating a relationship pattern:
--
-- >>> nodeB = Pattern { value = "B", elements = [] }
-- >>> relationship = Pattern { value = "knows", elements = [nodeA, nodeB] }
--
-- Creating a graph pattern:
--
-- >>> graph = Pattern { value = "myGraph", elements = [nodeA, nodeB, relationship] }
--
data Pattern v = Pattern 
  { -- | The decoration or metadata associated with this pattern.
    --
    -- The @value@ field stores decoration about what kind of pattern it is.
    -- This can be any type @v@, such as a string identifier, an integer, or a
    -- custom data type. The value is decoration about the pattern sequence itself,
    -- not part of the pattern. The elements form the pattern; the value describes it.
    --
    -- Type parameter @v@ allows for different decoration types. All patterns in a
    -- structure must share the same value type (enforced by the type system).
    --
    -- === Examples
    --
    -- >>> value (Pattern { value = "test", elements = [] })
    -- "test"
    --
    -- >>> value (Pattern { value = 42, elements = [] })
    -- 42
    --
    -- >>> value (Pattern { value = "graph", elements = [Pattern { value = "node", elements = [] }] })
    -- "graph"
    value    :: v
    
    -- | The pattern itself, represented as a sequence of elements.
    --
    -- The @elements@ field IS the pattern - it contains the sequence that defines
    -- the pattern. An empty list @[]@ represents a pattern with no elements
    -- (empty sequence). A non-empty list represents a pattern containing one or
    -- more pattern elements in sequence.
    --
    -- The elements maintain their sequence order and are accessible in that order.
    -- This order is essential to the pattern. Each element in the sequence is itself
    -- a Pattern, enabling recursive nesting where patterns can contain patterns
    -- containing patterns, etc., enabling arbitrary nesting depth while maintaining
    -- the pattern sequence semantic.
    --
    -- === Examples
    --
    -- Pattern with no elements (empty sequence):
    --
    -- >>> elements (Pattern { value = "empty", elements = [] })
    -- []
    --
    -- Pattern with one element:
    --
    -- >>> elem = Pattern { value = "elem", elements = [] }
    -- >>> elements (Pattern { value = "pattern", elements = [elem] })
    -- [Pattern {value = "elem", elements = []}]
    --
    -- Pattern with multiple elements:
    --
    -- >>> elem1 = Pattern { value = "elem1", elements = [] }
    -- >>> elem2 = Pattern { value = "elem2", elements = [] }
    -- >>> elements (Pattern { value = "pattern", elements = [elem1, elem2] })
    -- [Pattern {value = "elem1", elements = []},Pattern {value = "elem2", elements = []}]
  , elements :: [Pattern v]
  }
  deriving (Eq)

-- | Show instance for Pattern.
--
-- Displays patterns in a readable format showing both the value and elements.
-- The output format is: @Pattern {value = <value>, elements = [<elements>]}@
--
-- This instance requires that the value type @v@ has a @Show@ instance.
--
-- === Examples
--
-- >>> show (Pattern { value = "test", elements = [] })
-- "Pattern {value = \"test\", elements = []}"
--
-- >>> show (Pattern { value = 42, elements = [] })
-- "Pattern {value = 42, elements = []}"
--
instance Show v => Show (Pattern v) where
  show (Pattern v els) = 
    "Pattern {value = " ++ show v ++ ", elements = " ++ show els ++ "}"
