-- | Core Pattern data type and basic operations.
--
-- This module defines the fundamental Pattern type as a recursive structure
-- that can represent graph elements and sequences.
--
-- == Conceptual Model: Patterns as Decorated Sequences
--
-- Conceptually, a Pattern is a decorated sequence: the elements form the pattern
-- itself, and the value provides decoration about that pattern.
-- For example, the pattern "A B B A" with decoration "Enclosed rhyme" represents
-- a specific sequence pattern (A B B A) that is classified as an "Enclosed rhyme".
-- The Pattern type represents such decorated sequences where:
--
-- * @elements@ - The pattern itself, represented as a sequence of elements
-- * @value@ - Decoration about what kind of pattern it is
--
-- The elements ARE the pattern; they are not subordinate to the value.
-- While implemented using a recursive tree structure, the primary semantic is that
-- elements form the pattern sequence itself. Each element in the sequence is itself
-- a Pattern, enabling arbitrarily nested and complex pattern structures.
--
-- == Implementation: Recursive Tree Structure
--
-- The Pattern type is implemented as a recursive tree structure, but this is purely
-- an implementation detail. The relationship between the sequence conceptual model
-- and tree implementation is:
--
-- **Primary Semantic (Conceptual)**: Patterns are decorated sequences where elements
-- form the pattern itself. The sequence order is essential to the pattern.
--
-- **Implementation Detail**: The tree structure is how sequences are represented in
-- memory. Each tree node stores a decoration (value) and contains the pattern elements
-- as a list, enabling recursive nesting.
--
-- **Relationship**: The tree implementation supports sequence semantics:
--
-- * The @elements@ field IS the pattern - it contains the sequence that defines the pattern
-- * The @value@ field provides decoration about what kind of pattern it is
-- * Tree traversal provides access to sequence elements in order
-- * The recursive structure enables patterns to contain patterns containing patterns, etc.
--
-- Conceptually, developers should think of patterns as decorated sequences where elements
-- form the pattern itself. The tree structure is an implementation detail that supports
-- sequence operations (ordering, length, access by position).
--
-- This recursive implementation enables:
--
-- * Atomic patterns: Patterns with no elements (@elements == []@), representing empty sequences. Atomic patterns are the fundamental building blocks from which all other patterns are constructed.
-- * Patterns with elements: Patterns containing one or more pattern elements in sequence
-- * Arbitrary nesting: Patterns can contain patterns containing patterns, enabling
--   deeply nested pattern structures
--
-- == Values and Pattern Decoration
--
-- Each Pattern instance decorates a sequence of elements with a value:
--
-- * The @value@ field stores decoration about what kind of pattern it is. This can be any type @v@,
--   such as a string identifier, an integer, a custom data type, etc.
-- * The @value@ is decoration about the pattern sequence itself, not part of the pattern.
-- * All patterns in a structure must share the same value type @v@ (enforced by the type system).
--
-- For example, an atomic pattern might have @value = "Person"@
-- (decoration indicating the pattern type) and @elements = []@ (empty sequence pattern).
-- A pattern with two elements might have @value = "knows"@ (the pattern type decoration)
-- and @elements = [atomA, atomB]@ (the pattern itself - a sequence of two atomic patterns).
--
-- == Elements and Pattern Structure
--
-- The @elements@ field IS the pattern - it contains the sequence that defines the pattern:
--
-- * An empty sequence (@elements == []@) represents a pattern with no elements (empty sequence)
-- * A non-empty sequence represents a pattern containing one or more pattern elements
-- * The elements are ordered and maintain their sequence order - this order is essential to the pattern
-- * Each element in the sequence is itself a Pattern, enabling recursive nesting
--
-- The pattern structure enables compositional patterns:
--
-- * A pattern can include other patterns as its elements
-- * Those element patterns can themselves include patterns
-- * This enables arbitrary depth nesting while maintaining the pattern sequence semantic
--
-- For example, a pattern might have @elements = [atom1, atom2, pair1]@
-- where each element is a Pattern. A pair pattern itself might have
-- @elements = [atomA, atomB]@, creating a nested pattern structure.
--
-- == Type Safety and Type Parameter @v@
--
-- The Pattern type is parameterized over value type @v@:
--
-- * @Pattern v@ allows patterns to store values of any type @v@
-- * All patterns in a structure must share the same value type @v@
-- * This type consistency is enforced by Haskell's type system
-- * The type parameter ensures type safety when working with patterns
--
-- For example:
--
-- * @Pattern String@ - patterns storing string values
-- * @Pattern Int@ - patterns storing integer values
-- * @Pattern Person@ - patterns storing custom Person values
--
-- Type consistency means that if you have a @Pattern String@, all patterns in
-- its @elements@ list must also be @Pattern String@. This prevents mixing
-- different value types within a single pattern structure.
--
-- == Mathematical Foundation
--
-- Patterns form the foundation for category-theoretic graph representations.
-- The recursive structure enables functor instances (to be added in future phases)
-- and supports various graph interpretations through categorical views. The sequence
-- semantic aligns with categorical composition and transformation operations.
--
-- == Examples
--
-- Atomic pattern:
--
-- >>> atom = Pattern { value = "atom1", elements = [] }
-- >>> value atom
-- "atom1"
-- >>> elements atom
-- []
--
-- Pattern with elements:
--
-- >>> elem1 = Pattern { value = "elem1", elements = [] }
-- >>> elem2 = Pattern { value = "elem2", elements = [] }
-- >>> pattern = Pattern { value = "pattern", elements = [elem1, elem2] }
-- >>> value pattern
-- "pattern"
-- >>> length (elements pattern)
-- 2
-- >>> map value (elements pattern)
-- ["elem1","elem2"]
--
-- Nested patterns (arbitrary depth):
--
-- >>> level3 = Pattern { value = "level3", elements = [] }
-- >>> level2 = Pattern { value = "level2", elements = [level3] }
-- >>> level1 = Pattern { value = "level1", elements = [level2] }
-- >>> nested = Pattern { value = "root", elements = [level1] }
-- >>> value nested
-- "root"
-- >>> value (head (elements nested))
-- "level1"
--
-- Atomic patterns with different value types:
--
-- >>> leafString = Pattern { value = "text", elements = [] }
-- >>> leafInt = Pattern { value = 42, elements = [] }
-- >>> value leafString
-- "text"
-- >>> value leafInt
-- 42
--
-- Patterns with varying numbers of elements:
--
-- >>> zeroElements = Pattern { value = "zero", elements = [] }
-- >>> oneElement = Pattern { value = "one", elements = [Pattern { value = "elem", elements = [] }] }
-- >>> manyElements = Pattern { value = "many", elements = [Pattern { value = "e1", elements = [] }, Pattern { value = "e2", elements = [] }] }
-- >>> length (elements zeroElements)
-- 0
-- >>> length (elements oneElement)
-- 1
-- >>> length (elements manyElements)
-- 2
module Pattern.Core where

-- | A recursive structure representing a decorated sequence pattern.
--
-- Conceptually, a Pattern is a decorated sequence: the elements form the pattern
-- itself, and the value provides decoration about that pattern.
-- For example, the pattern "A B B A" with decoration "Enclosed rhyme" represents
-- a specific sequence pattern (A B B A) that is classified as an "Enclosed rhyme".
-- The Pattern type represents such decorated sequences where each element is itself
-- a Pattern, enabling recursive nesting.
--
-- Patterns form the foundation for representing graph elements and sequences.
-- Each pattern decorates a sequence of pattern elements with a value of any type.
-- The recursive structure enables compositional and nested patterns while maintaining
-- the decorated sequence semantic.
--
-- The Pattern type is intentionally minimal - it provides just the structure
-- needed for recursive sequence representation. Classification functions
-- (identifying nodes, relationships, subgraphs) will be added in future phases.
--
-- === Type Parameter @v@
--
-- The @v@ type parameter allows patterns to store decorations of any type.
-- All patterns in a structure must share the same value type @v@. This type
-- consistency is enforced by Haskell's type system, ensuring type safety when
-- working with patterns.
--
-- For example, @Pattern String@ represents patterns with string decorations,
-- @Pattern Int@ represents patterns with integer decorations, and @Pattern Person@
-- represents patterns with custom Person decorations. All elements in a pattern's
-- sequence must have the same decoration type as the pattern itself.
--
-- === Pattern Structural Classifications
--
-- Patterns have structural classifications based on their element structure:
--
-- * Atomic pattern: @elements == []@ - a sequence with no elements. Atomic patterns are the fundamental building blocks from which all other patterns are constructed.
-- * Singular pattern: @length (elements p) == 1@ - a sequence with exactly one element
-- * Pattern with elements: @elements@ contains one or more pattern elements
-- * Nested pattern: patterns containing patterns containing patterns, enabling arbitrary nesting
--
-- === Graph Interpretations (Views)
--
-- Patterns can be **interpreted** as graph elements through different views.
-- These are interpretations/views of pattern structures, not pattern variants themselves:
--
-- * Atomic patterns can be interpreted as nodes through graph views
-- * Patterns with 2 elements can be interpreted as relationships through graph views
-- * Patterns with elements can be interpreted as subgraphs through graph views
--
-- **Note**: Patterns are a data structure for representing graphs (like an adjacency matrix
-- or adjacency list), optimized for expressiveness of layered, hierarchical graph structures
-- rather than performance optimization over a single, "flat" graph.
--
-- === Examples
--
-- Creating an atomic pattern:
--
-- >>> atom = Pattern { value = "A", elements = [] }
--
-- Creating a pattern with elements (can be interpreted as a relationship):
--
-- >>> elem1 = Pattern { value = "A", elements = [] }
-- >>> elem2 = Pattern { value = "B", elements = [] }
-- >>> pattern = Pattern { value = "knows", elements = [elem1, elem2] }
--
-- Creating a pattern with multiple elements (can be interpreted as a subgraph):
--
-- >>> graph = Pattern { value = "myGraph", elements = [elem1, elem2, pattern] }
--
data Pattern v = Pattern 
  { -- | The decoration (value) associated with this pattern.
    --
    -- The @value@ field stores decoration about what kind of pattern it is.
    -- This can be any type @v@, such as a string identifier, an integer, or a
    -- custom data type. The value is decoration about the pattern sequence itself,
    -- not part of the pattern. The elements form the pattern; the value describes it.
    --
    -- Type parameter @v@ allows for different decoration types. All patterns in a
    -- structure must share the same value type (enforced by the type system).
    --
    -- === Examples
    --
    -- >>> value (Pattern { value = "test", elements = [] })
    -- "test"
    --
    -- >>> value (Pattern { value = 42, elements = [] })
    -- 42
    --
    -- >>> value (Pattern { value = "group", elements = [Pattern { value = "atom", elements = [] }] })
    -- "group"
    value    :: v
    
    -- | The pattern itself, represented as a sequence of elements.
    --
    -- The @elements@ field IS the pattern - it contains the sequence that defines
    -- the pattern. An empty list @[]@ represents a pattern with no elements
    -- (empty sequence). A non-empty list represents a pattern containing one or
    -- more pattern elements in sequence.
    --
    -- The elements maintain their sequence order and are accessible in that order.
    -- This order is essential to the pattern. Each element in the sequence is itself
    -- a Pattern, enabling recursive nesting where patterns can contain patterns
    -- containing patterns, etc., enabling arbitrary nesting depth while maintaining
    -- the pattern sequence semantic.
    --
    -- === Examples
    --
    -- Pattern with no elements (empty sequence):
    --
    -- >>> elements (Pattern { value = "empty", elements = [] })
    -- []
    --
    -- Singular pattern (one element):
    --
    -- >>> elem = Pattern { value = "elem", elements = [] }
    -- >>> elements (Pattern { value = "pattern", elements = [elem] })
    -- [Pattern {value = "elem", elements = []}]
    --
    -- Pattern with multiple elements:
    --
    -- >>> elem1 = Pattern { value = "elem1", elements = [] }
    -- >>> elem2 = Pattern { value = "elem2", elements = [] }
    -- >>> elements (Pattern { value = "pattern", elements = [elem1, elem2] })
    -- [Pattern {value = "elem1", elements = []},Pattern {value = "elem2", elements = []}]
  , elements :: [Pattern v]
  }
  deriving (Eq)

-- | Show instance for Pattern.
--
-- Displays patterns in a readable format showing both the value and elements.
-- The output format is: @Pattern {value = <value>, elements = [<elements>]}@
--
-- This instance requires that the value type @v@ has a @Show@ instance.
--
-- === Examples
--
-- >>> show (Pattern { value = "test", elements = [] })
-- "Pattern {value = \"test\", elements = []}"
--
-- >>> show (Pattern { value = 42, elements = [] })
-- "Pattern {value = 42, elements = []}"
--
instance Show v => Show (Pattern v) where
  show (Pattern v els) = 
    "Pattern {value = " ++ show v ++ ", elements = " ++ show els ++ "}"

-- | Create an atomic pattern (pattern with no elements) from a value.
--
-- This function provides a convenient way to create atomic patterns without
-- using verbose record syntax. The resulting pattern is functionally identical
-- to one created with @Pattern { value = x, elements = [] }@.
--
-- === Examples
--
-- Create an atomic pattern with a string value:
--
-- >>> atom = pattern "atom1"
-- >>> value atom
-- "atom1"
-- >>> elements atom
-- []
--
-- Create an atomic pattern with an integer value:
--
-- >>> num = pattern 42
-- >>> value num
-- 42
--
-- Create an atomic pattern with a custom type:
--
-- >>> data Person = Person { name :: String, age :: Maybe Int }
-- >>> person = pattern (Person "Alice" (Just 30))
-- >>> value person
-- Person {name = "Alice", age = Just 30}
--
-- === Functional Equivalence
--
-- The following are equivalent:
--
-- >>> pattern "test" == Pattern { value = "test", elements = [] }
-- True
pattern :: v -> Pattern v
pattern v = Pattern { value = v, elements = [] }

-- | Create a pattern with elements from a value and a list of pattern elements.
--
-- This function provides a convenient way to create patterns with elements
-- without using verbose record syntax. The resulting pattern is functionally
-- identical to one created with @Pattern { value = x, elements = ps }@.
--
-- The function preserves the order of elements in the input list and handles
-- all element counts: 0 (atomic pattern), 1 (singular pattern), 2 (pair),
-- or many (extended pattern).
--
-- === Examples
--
-- Create a singular pattern (one element):
--
-- >>> singular = patternWith "soccer" [pattern "a team sport involving kicking a ball"]
-- >>> length (elements singular)
-- 1
--
-- Create a pair pattern (two elements):
--
-- >>> pair = patternWith "knows" [pattern "Alice", pattern "Bob"]
-- >>> length (elements pair)
-- 2
--
-- Create an extended pattern (many elements):
--
-- >>> extended = patternWith "graph" [pattern "elem1", pattern "elem2", pattern "elem3"]
-- >>> length (elements extended)
-- 3
--
-- Empty list produces atomic pattern:
--
-- >>> atomic = patternWith "empty" []
-- >>> elements atomic
-- []
-- >>> atomic == pattern "empty"
-- True
--
-- === Functional Equivalence
--
-- The following are equivalent:
--
-- >>> patternWith "test" [pattern "elem"] == Pattern { value = "test", elements = [Pattern { value = "elem", elements = [] }] }
-- True
--
-- === Element Order
--
-- Element order is preserved:
--
-- >>> p1 = patternWith "seq" [pattern "a", pattern "b"]
-- >>> p2 = patternWith "seq" [pattern "b", pattern "a"]
-- >>> p1 == p2
-- False
patternWith :: v -> [Pattern v] -> Pattern v
patternWith v ps = Pattern { value = v, elements = ps }

-- | Create a pattern from a list of values by converting each value to an atomic pattern.
--
-- This function provides a convenient way to create patterns from lists of raw values.
-- Each value in the list is automatically converted to an atomic pattern, then all
-- atomic patterns are combined into a single pattern with the given decoration.
--
-- The function preserves the order of values in the input list and handles all
-- element counts: 0 (atomic pattern), 1 (singular pattern), 2 (pair), or many
-- (extended pattern).
--
-- === Examples
--
-- Create a pattern from a list of strings:
--
-- >>> p = fromList "graph" ["Alice", "Bob", "Charlie"]
-- >>> value p
-- "graph"
-- >>> length (elements p)
-- 3
-- >>> map value (elements p)
-- ["Alice","Bob","Charlie"]
--
-- Create a pattern from a list of integers:
--
-- >>> nums = fromList "numbers" [1, 2, 3, 4, 5]
-- >>> length (elements nums)
-- 5
--
-- Empty list produces atomic pattern:
--
-- >>> atomic = fromList "empty" []
-- >>> elements atomic
-- []
-- >>> atomic == pattern "empty"
-- True
--
-- === Functional Equivalence
--
-- The following are equivalent:
--
-- >>> fromList "test" ["a", "b"] == patternWith "test" [pattern "a", pattern "b"]
-- True
--
-- === Implementation
--
-- This function is implemented as:
--
-- @
-- fromList decoration values = patternWith decoration (map pattern values)
-- @
fromList :: v -> [v] -> Pattern v
fromList decoration values = patternWith decoration (map pattern values)
