-- | Core Pattern data type and basic operations.
--
-- This module defines the fundamental Pattern type as a recursive structure
-- that can represent graph elements and sequences.
--
-- == Conceptual Model: Patterns as Decorated Sequences
--
-- Conceptually, a Pattern is a decorated sequence: the elements form the pattern
-- itself, and the value provides decoration about that pattern.
-- For example, the pattern "A B B A" with decoration "Enclosed rhyme" represents
-- a specific sequence pattern (A B B A) that is classified as an "Enclosed rhyme".
-- The Pattern type represents such decorated sequences where:
--
-- * @elements@ - The pattern itself, represented as a sequence of elements
-- * @value@ - Decoration about what kind of pattern it is
--
-- The elements ARE the pattern; they are not subordinate to the value.
-- While implemented using a recursive tree structure, the primary semantic is that
-- elements form the pattern sequence itself. Each element in the sequence is itself
-- a Pattern, enabling arbitrarily nested and complex pattern structures.
--
-- == Implementation: Recursive Tree Structure
--
-- The Pattern type is implemented as a recursive tree structure, but this is purely
-- an implementation detail. The relationship between the sequence conceptual model
-- and tree implementation is:
--
-- **Primary Semantic (Conceptual)**: Patterns are decorated sequences where elements
-- form the pattern itself. The sequence order is essential to the pattern.
--
-- **Implementation Detail**: The tree structure is how sequences are represented in
-- memory. Each tree node stores a decoration (value) and contains the pattern elements
-- as a list, enabling recursive nesting.
--
-- **Relationship**: The tree implementation supports sequence semantics:
--
-- * The @elements@ field IS the pattern - it contains the sequence that defines the pattern
-- * The @value@ field provides decoration about what kind of pattern it is
-- * Tree traversal provides access to sequence elements in order
-- * The recursive structure enables patterns to contain patterns containing patterns, etc.
--
-- Conceptually, developers should think of patterns as decorated sequences where elements
-- form the pattern itself. The tree structure is an implementation detail that supports
-- sequence operations (ordering, length, access by position).
--
-- This recursive implementation enables:
--
-- * Atomic patterns: Patterns with no elements (@elements == []@), representing empty sequences. Atomic patterns are the fundamental building blocks from which all other patterns are constructed.
-- * Patterns with elements: Patterns containing one or more pattern elements in sequence
-- * Arbitrary nesting: Patterns can contain patterns containing patterns, enabling
--   deeply nested pattern structures
--
-- == Values and Pattern Decoration
--
-- Each Pattern instance decorates a sequence of elements with a value:
--
-- * The @value@ field stores decoration about what kind of pattern it is. This can be any type @v@,
--   such as a string identifier, an integer, a custom data type, etc.
-- * The @value@ is decoration about the pattern sequence itself, not part of the pattern.
-- * All patterns in a structure must share the same value type @v@ (enforced by the type system).
--
-- For example, an atomic pattern might have @value = "Person"@
-- (decoration indicating the pattern type) and @elements = []@ (empty sequence pattern).
-- A pattern with two elements might have @value = "knows"@ (the pattern type decoration)
-- and @elements = [atomA, atomB]@ (the pattern itself - a sequence of two atomic patterns).
--
-- == Elements and Pattern Structure
--
-- The @elements@ field IS the pattern - it contains the sequence that defines the pattern:
--
-- * An empty sequence (@elements == []@) represents a pattern with no elements (empty sequence)
-- * A non-empty sequence represents a pattern containing one or more pattern elements
-- * The elements are ordered and maintain their sequence order - this order is essential to the pattern
-- * Each element in the sequence is itself a Pattern, enabling recursive nesting
--
-- The pattern structure enables compositional patterns:
--
-- * A pattern can include other patterns as its elements
-- * Those element patterns can themselves include patterns
-- * This enables arbitrary depth nesting while maintaining the pattern sequence semantic
--
-- For example, a pattern might have @elements = [atom1, atom2, pair1]@
-- where each element is a Pattern. A pair pattern itself might have
-- @elements = [atomA, atomB]@, creating a nested pattern structure.
--
-- == Type Safety and Type Parameter @v@
--
-- The Pattern type is parameterized over value type @v@:
--
-- * @Pattern v@ allows patterns to store values of any type @v@
-- * All patterns in a structure must share the same value type @v@
-- * This type consistency is enforced by Haskell's type system
-- * The type parameter ensures type safety when working with patterns
--
-- For example:
--
-- * @Pattern String@ - patterns storing string values
-- * @Pattern Int@ - patterns storing integer values
-- * @Pattern Person@ - patterns storing custom Person values
--
-- Type consistency means that if you have a @Pattern String@, all patterns in
-- its @elements@ list must also be @Pattern String@. This prevents mixing
-- different value types within a single pattern structure.
--
-- == Mathematical Foundation
--
-- Patterns form the foundation for category-theoretic graph representations.
-- The recursive structure enables functor instances and supports various graph
-- interpretations through categorical views. The sequence semantic aligns with
-- categorical composition and transformation operations.
--
-- The Pattern type has a Functor instance that enables value transformation while
-- preserving pattern structure. This supports functional transformations and type
-- conversions essential for pattern manipulation. See the Functor instance documentation
-- below for details on structure preservation and functor laws.
--
-- The Pattern type has a Foldable instance that enables value aggregation over pattern
-- structures. This supports operations like summing values, concatenating strings, counting
-- elements, and computing statistics without manually traversing the pattern tree. The instance
-- provides @foldr@ for right-associative folding, @foldl@ for left-associative folding,
-- @foldMap@ for monoid-based aggregation, and @toList@ for extracting all values as a flat list.
-- The module also provides @flatten@ as an explicit function for extracting all values as a flat
-- list, equivalent to @toList@. See the Foldable instance documentation below for details on
-- value aggregation and folding operations.
--
-- The Pattern type has a Traversable instance that enables effectful traversal over pattern
-- structures while preserving pattern structure. This supports operations like validation,
-- state threading, IO operations, and error handling over pattern values. The instance provides
-- @traverse@ for applying effectful functions to all values and @sequenceA@ for sequencing
-- applicative effects. See the Traversable instance documentation below for details on effectful
-- traversal and structure preservation.
--
-- The Pattern type has an Ord instance that provides lexicographic ordering for patterns based
-- on their structure. Patterns are ordered by comparing their value first, then their elements
-- recursively. This ordering is consistent with the Eq instance and enables patterns to be
-- used as keys in Data.Map and elements in Data.Set. The Ord instance requires that the value
-- type @v@ has an Ord instance. See the Ord instance documentation below for details on
-- ordering rules and consistency with equality.
--
-- The Pattern type provides query functions for introspecting pattern structure:
--
-- * @length@ - Returns the number of direct elements in a pattern's sequence (O(1))
-- * @size@ - Returns the total number of nodes in a pattern structure, including all nested patterns (O(n))
-- * @depth@ - Returns the maximum nesting depth of a pattern structure (O(n))
-- * @values@ - Extracts all values from a pattern structure as a flat list (O(n))
-- * @value@ - Field accessor for accessing a pattern's decoration value (O(1))
--
-- These query functions enable pattern introspection, validation, and analysis operations.
-- See individual function documentation for details on usage and performance characteristics.
--
-- == Examples
--
-- Atomic pattern:
--
-- >>> atom = Pattern { value = "atom1", elements = [] }
-- >>> value atom
-- "atom1"
-- >>> elements atom
-- []
--
-- Pattern with elements:
--
-- >>> elem1 = Pattern { value = "elem1", elements = [] }
-- >>> elem2 = Pattern { value = "elem2", elements = [] }
-- >>> pattern = Pattern { value = "pattern", elements = [elem1, elem2] }
-- >>> value pattern
-- "pattern"
-- >>> length (elements pattern)
-- 2
-- >>> map value (elements pattern)
-- ["elem1","elem2"]
--
-- Nested patterns (arbitrary depth):
--
-- >>> level3 = Pattern { value = "level3", elements = [] }
-- >>> level2 = Pattern { value = "level2", elements = [level3] }
-- >>> level1 = Pattern { value = "level1", elements = [level2] }
-- >>> nested = Pattern { value = "root", elements = [level1] }
-- >>> value nested
-- "root"
-- >>> value (head (elements nested))
-- "level1"
--
-- Atomic patterns with different value types:
--
-- >>> leafString = Pattern { value = "text", elements = [] }
-- >>> leafInt = Pattern { value = 42, elements = [] }
-- >>> value leafString
-- "text"
-- >>> value leafInt
-- 42
--
-- Patterns with varying numbers of elements:
--
-- >>> zeroElements = Pattern { value = "zero", elements = [] }
-- >>> oneElement = Pattern { value = "one", elements = [Pattern { value = "elem", elements = [] }] }
-- >>> manyElements = Pattern { value = "many", elements = [Pattern { value = "e1", elements = [] }, Pattern { value = "e2", elements = [] }] }
-- >>> length (elements zeroElements)
-- 0
-- >>> length (elements oneElement)
-- 1
-- >>> length (elements manyElements)
-- 2
module Pattern.Core where

import Data.Foldable (toList)
import Data.Traversable (Traversable(..))

-- | A recursive structure representing a decorated sequence pattern.
--
-- Conceptually, a Pattern is a decorated sequence: the elements form the pattern
-- itself, and the value provides decoration about that pattern.
-- For example, the pattern "A B B A" with decoration "Enclosed rhyme" represents
-- a specific sequence pattern (A B B A) that is classified as an "Enclosed rhyme".
-- The Pattern type represents such decorated sequences where each element is itself
-- a Pattern, enabling recursive nesting.
--
-- Patterns form the foundation for representing graph elements and sequences.
-- Each pattern decorates a sequence of pattern elements with a value of any type.
-- The recursive structure enables compositional and nested patterns while maintaining
-- the decorated sequence semantic.
--
-- The Pattern type is intentionally minimal - it provides just the structure
-- needed for recursive sequence representation. Classification functions
-- (identifying nodes, relationships, subgraphs) will be added in future phases.
--
-- === Type Parameter @v@
--
-- The @v@ type parameter allows patterns to store decorations of any type.
-- All patterns in a structure must share the same value type @v@. This type
-- consistency is enforced by Haskell's type system, ensuring type safety when
-- working with patterns.
--
-- For example, @Pattern String@ represents patterns with string decorations,
-- @Pattern Int@ represents patterns with integer decorations, and @Pattern Person@
-- represents patterns with custom Person decorations. All elements in a pattern's
-- sequence must have the same decoration type as the pattern itself.
--
-- === Pattern Structural Classifications
--
-- Patterns have structural classifications based on their element structure:
--
-- * Atomic pattern: @elements == []@ - a sequence with no elements. Atomic patterns are the fundamental building blocks from which all other patterns are constructed.
-- * Singular pattern: @length (elements p) == 1@ - a sequence with exactly one element
-- * Pattern with elements: @elements@ contains one or more pattern elements
-- * Nested pattern: patterns containing patterns containing patterns, enabling arbitrary nesting
--
-- === Graph Interpretations (Views)
--
-- Patterns can be **interpreted** as graph elements through different views.
-- These are interpretations/views of pattern structures, not pattern variants themselves:
--
-- * Atomic patterns can be interpreted as nodes through graph views
-- * Patterns with 2 elements can be interpreted as relationships through graph views
-- * Patterns with elements can be interpreted as subgraphs through graph views
--
-- **Note**: Patterns are a data structure for representing graphs (like an adjacency matrix
-- or adjacency list), optimized for expressiveness of layered, hierarchical graph structures
-- rather than performance optimization over a single, "flat" graph.
--
-- === Examples
--
-- Creating an atomic pattern:
--
-- >>> atom = Pattern { value = "A", elements = [] }
--
-- Creating a pattern with elements (can be interpreted as a relationship):
--
-- >>> elem1 = Pattern { value = "A", elements = [] }
-- >>> elem2 = Pattern { value = "B", elements = [] }
-- >>> pattern = Pattern { value = "knows", elements = [elem1, elem2] }
--
-- Creating a pattern with multiple elements (can be interpreted as a subgraph):
--
-- >>> graph = Pattern { value = "myGraph", elements = [elem1, elem2, pattern] }
--
data Pattern v = Pattern 
  { -- | The decoration (value) associated with this pattern.
    --
    -- The @value@ field stores decoration about what kind of pattern it is.
    -- This can be any type @v@, such as a string identifier, an integer, or a
    -- custom data type. The value is decoration about the pattern sequence itself,
    -- not part of the pattern. The elements form the pattern; the value describes it.
    --
    -- Type parameter @v@ allows for different decoration types. All patterns in a
    -- structure must share the same value type (enforced by the type system).
    --
    -- The @value@ field accessor provides direct access to a pattern's decoration
    -- value without any computation. This is the primary way to access pattern
    -- decoration values for querying, analysis, and transformation operations.
    --
    -- === Accessing Pattern Values
    --
    -- The @value@ field accessor works with patterns of any value type and at any
    -- nesting level. Each pattern in a nested structure has its own value that can
    -- be accessed independently.
    --
    -- === Examples
    --
    -- Atomic pattern with string value:
    --
    -- >>> value (Pattern { value = "test", elements = [] })
    -- "test"
    --
    -- Atomic pattern with integer value:
    --
    -- >>> value (Pattern { value = 42, elements = [] })
    -- 42
    --
    -- Pattern with elements (accesses root value):
    --
    -- >>> value (Pattern { value = "group", elements = [Pattern { value = "atom", elements = [] }] })
    -- "group"
    --
    -- Accessing values at different nesting levels:
    --
    -- >>> inner = Pattern { value = "inner", elements = [] }
    -- >>> middle = Pattern { value = "middle", elements = [inner] }
    -- >>> outer = Pattern { value = "outer", elements = [middle] }
    -- >>> pattern = Pattern { value = "root", elements = [outer] }
    -- >>> value pattern
    -- "root"
    -- >>> value outer
    -- "outer"
    -- >>> value middle
    -- "middle"
    -- >>> value inner
    -- "inner"
    --
    -- Pattern with custom type value:
    --
    -- >>> data Person = Person { name :: String, age :: Maybe Int } deriving (Show)
    -- >>> person = Person "Alice" (Just 30)
    -- >>> value (Pattern { value = person, elements = [] })
    -- Person {name = "Alice", age = Just 30}
    --
    -- === Relationship to values function
    --
    -- The @value@ field accessor returns a single value (the pattern's own value),
    -- while the @values@ function returns all values from the entire pattern structure:
    --
    -- @
    -- value p == head (values p)
    -- @
    --
    -- The @value@ field provides O(1) access to the pattern's decoration, while
    -- @values@ extracts all values recursively.
    --
    -- === Performance
    --
    -- The @value@ field accessor is a direct field access operation with O(1) time
    -- complexity. No computation is required - it simply returns the stored value.
    --
    -- === Type Safety
    --
    -- The @value@ field accessor works with patterns of any value type @v@:
    --
    -- >>> value (Pattern { value = "test", elements = [] } :: Pattern String)
    -- "test"
    -- >>> value (Pattern { value = 42, elements = [] } :: Pattern Int)
    -- 42
    --
    value    :: v
    
    -- | The pattern itself, represented as a sequence of elements.
    --
    -- The @elements@ field IS the pattern - it contains the sequence that defines
    -- the pattern. An empty list @[]@ represents a pattern with no elements
    -- (empty sequence). A non-empty list represents a pattern containing one or
    -- more pattern elements in sequence.
    --
    -- The elements maintain their sequence order and are accessible in that order.
    -- This order is essential to the pattern. Each element in the sequence is itself
    -- a Pattern, enabling recursive nesting where patterns can contain patterns
    -- containing patterns, etc., enabling arbitrary nesting depth while maintaining
    -- the pattern sequence semantic.
    --
    -- === Examples
    --
    -- Pattern with no elements (empty sequence):
    --
    -- >>> elements (Pattern { value = "empty", elements = [] })
    -- []
    --
    -- Singular pattern (one element):
    --
    -- >>> elem = Pattern { value = "elem", elements = [] }
    -- >>> elements (Pattern { value = "pattern", elements = [elem] })
    -- [Pattern {value = "elem", elements = []}]
    --
    -- Pattern with multiple elements:
    --
    -- >>> elem1 = Pattern { value = "elem1", elements = [] }
    -- >>> elem2 = Pattern { value = "elem2", elements = [] }
    -- >>> elements (Pattern { value = "pattern", elements = [elem1, elem2] })
    -- [Pattern {value = "elem1", elements = []},Pattern {value = "elem2", elements = []}]
  , elements :: [Pattern v]
  }
  deriving (Eq)

-- | Show instance for Pattern.
--
-- Displays patterns in a readable format showing both the value and elements.
-- The output format is: @Pattern {value = <value>, elements = [<elements>]}@
--
-- This instance requires that the value type @v@ has a @Show@ instance.
--
-- === Examples
--
-- >>> show (Pattern { value = "test", elements = [] })
-- "Pattern {value = \"test\", elements = []}"
--
-- >>> show (Pattern { value = 42, elements = [] })
-- "Pattern {value = 42, elements = []}"
--
instance Show v => Show (Pattern v) where
  show (Pattern v els) = 
    "Pattern {value = " ++ show v ++ ", elements = " ++ show els ++ "}"

-- | Ord instance for Pattern.
--
-- Provides lexicographic ordering for patterns based on their structure.
-- Patterns are ordered by comparing their value first, then their elements
-- recursively. This ordering is consistent with the `Eq` instance and enables
-- patterns to be used as keys in `Data.Map` and elements in `Data.Set`.
--
-- === Ordering Rules
--
-- The `Ord` instance uses lexicographic ordering:
--
-- 1. **Value comparison first**: If two patterns have different values,
--    ordering is determined by comparing the values using the `Ord` instance
--    for the value type.
--
-- 2. **Element comparison second**: If two patterns have the same value,
--    ordering is determined by comparing their elements lists lexicographically.
--    Elements are compared recursively using the same ordering rules.
--
-- 3. **Structure preservation**: Patterns with different structures are
--    distinguished even if they have the same flattened values. This ensures
--    that ordering respects the pattern's structure as represented by `toTuple`.
--
-- === Consistency with Eq
--
-- The `Ord` instance is consistent with the `Eq` instance:
--
-- * Patterns that are equal according to `Eq` compare as `EQ`
-- * Patterns that are not equal according to `Eq` compare as `LT` or `GT`
-- * Ordering uses the same comparison order as `Eq` (value first, then elements)
--
-- === Examples
--
-- Atomic patterns with different values:
--
-- >>> compare (pattern "a") (pattern "b")
-- LT
-- >>> compare (pattern "b") (pattern "a")
-- GT
--
-- Patterns with same value but different elements:
--
-- >>> p1 = patternWith "root" [pattern "a"]
-- >>> p2 = patternWith "root" [pattern "b"]
-- >>> compare p1 p2
-- LT
--
-- Patterns with same value and same elements:
--
-- >>> p1 = patternWith "root" [pattern "a", pattern "b"]
-- >>> p2 = patternWith "root" [pattern "a", pattern "b"]
-- >>> compare p1 p2
-- EQ
--
-- Nested patterns (recursive comparison):
--
-- >>> inner1 = pattern "inner1"
-- >>> inner2 = pattern "inner2"
-- >>> outer1 = patternWith "outer" [patternWith "middle" [inner1]]
-- >>> outer2 = patternWith "outer" [patternWith "middle" [inner2]]
-- >>> compare outer1 outer2
-- LT
--
-- Using comparison operators:
--
-- >>> (pattern "a") < (pattern "b")
-- True
-- >>> (pattern "a") <= (pattern "b")
-- True
-- >>> (pattern "b") > (pattern "a")
-- True
--
-- Using min and max:
--
-- >>> min (pattern "a") (pattern "b")
-- Pattern {value = "a", elements = []}
-- >>> max (pattern "a") (pattern "b")
-- Pattern {value = "b", elements = []}
--
-- === Type Constraint
--
-- The `Ord` instance requires that the value type `v` has an `Ord` instance:
--
-- @
-- instance Ord v => Ord (Pattern v)
-- @
--
-- This ensures that pattern values can be compared, which is necessary for
-- lexicographic ordering. Attempting to use `Ord` operations on patterns with
-- non-orderable value types will result in a compile-time error.
--
-- === Relationship to toTuple
--
-- The ordering semantics are based on `toTuple()` structure-preserving
-- representation. Comparing two patterns is equivalent to comparing their
-- tuple representations:
--
-- @
-- compare p1 p2 == compare (toTuple p1) (toTuple p2)
-- @
--
-- This ensures that ordering distinguishes patterns with different structures
-- even if they have the same flattened values.
--
instance Ord v => Ord (Pattern v) where
  compare (Pattern v1 els1) (Pattern v2 els2) =
    compare v1 v2 `mappend` compare els1 els2

-- | Functor instance for Pattern.
--
-- Transforms values in patterns while preserving pattern structure (element count,
-- nesting depth, element order). The transformation function is applied recursively
-- to all values in the pattern structure, including values at all nesting levels.
--
-- The Functor instance enables value transformation without manual pattern reconstruction.
-- This is essential for pattern composition, type conversion, and functional transformations
-- that are fundamental to practical pattern manipulation.
--
-- === Structure Preservation
--
-- The Functor instance preserves pattern structure during transformation:
--
-- * Element count: The number of elements remains unchanged
-- * Nesting depth: The nesting structure is preserved
-- * Element order: The order of elements is maintained
--
-- Only the values are transformed; the pattern structure itself remains identical.
--
-- === Functor Laws
--
-- The Functor instance satisfies the standard functor laws, which are verified
-- through property-based testing in the test suite:
--
-- **Identity Law**: For all patterns @p :: Pattern v@,
--
-- @
-- fmap id p = id p
-- @
--
-- This law states that applying the identity function to a pattern produces
-- the exact same pattern. The identity function leaves all values unchanged,
-- so the pattern structure and values remain identical.
--
-- **Composition Law**: For all patterns @p :: Pattern a@ and functions
-- @f :: b -> c@ and @g :: a -> b@,
--
-- @
-- fmap (f . g) p = (fmap f . fmap g) p
-- @
--
-- This law states that applying a composition of two functions to a pattern
-- produces the same result as applying each function sequentially. This enables
-- safe composition of transformations and predictable behavior when chaining
-- multiple transformations.
--
-- Both laws hold for all pattern structures (atomic, with elements, nested)
-- and all value types, as verified by property-based tests.
--
-- === Examples
--
-- Transforming atomic pattern with string value:
--
-- >>> atom = Pattern { value = "test", elements = [] }
-- >>> fmap (map toUpper) atom
-- Pattern {value = "TEST", elements = []}
--
-- Transforming pattern with multiple elements:
--
-- >>> elem1 = Pattern { value = "hello", elements = [] }
-- >>> elem2 = Pattern { value = "world", elements = [] }
-- >>> pattern = Pattern { value = "greeting", elements = [elem1, elem2] }
-- >>> fmap (map toUpper) pattern
-- Pattern {value = "GREETING", elements = [Pattern {value = "HELLO", elements = []},Pattern {value = "WORLD", elements = []}]}
--
-- Transforming pattern with integer values:
--
-- >>> elem1 = Pattern { value = 5, elements = [] }
-- >>> elem2 = Pattern { value = 10, elements = [] }
-- >>> pattern = Pattern { value = 20, elements = [elem1, elem2] }
-- >>> fmap (* 2) pattern
-- Pattern {value = 40, elements = [Pattern {value = 10, elements = []},Pattern {value = 20, elements = []}]}
--
-- Transforming nested pattern structure (3 levels):
--
-- >>> inner = Pattern { value = "inner", elements = [] }
-- >>> middle = Pattern { value = "middle", elements = [inner] }
-- >>> outer = Pattern { value = "outer", elements = [middle] }
-- >>> pattern = Pattern { value = "root", elements = [outer] }
-- >>> fmap (map toUpper) pattern
-- Pattern {value = "ROOT", elements = [Pattern {value = "OUTER", elements = [Pattern {value = "MIDDLE", elements = [Pattern {value = "INNER", elements = []}]}]}]}
--
-- Transforming deeply nested pattern structure (4+ levels):
--
-- >>> level4 = Pattern { value = "level4", elements = [] }
-- >>> level3 = Pattern { value = "level3", elements = [level4] }
-- >>> level2 = Pattern { value = "level2", elements = [level3] }
-- >>> level1 = Pattern { value = "level1", elements = [level2] }
-- >>> pattern = Pattern { value = "root", elements = [level1] }
-- >>> fmap (map toUpper) pattern
-- Pattern {value = "ROOT", elements = [Pattern {value = "LEVEL1", elements = [Pattern {value = "LEVEL2", elements = [Pattern {value = "LEVEL3", elements = [Pattern {value = "LEVEL4", elements = []}]}]}]}]}
--
-- Transforming pattern with varying nesting depths in different branches:
--
-- >>> branch1 = Pattern { value = "b1", elements = [Pattern { value = "b1leaf", elements = [] }] }
-- >>> branch2 = Pattern { value = "b2", elements = [Pattern { value = "b2mid", elements = [Pattern { value = "b2leaf", elements = [] }] }] }
-- >>> branch3 = Pattern { value = "b3", elements = [] }
-- >>> pattern = Pattern { value = "root", elements = [branch1, branch2, branch3] }
-- >>> fmap (map toUpper) pattern
-- Pattern {value = "ROOT", elements = [Pattern {value = "B1", elements = [Pattern {value = "B1LEAF", elements = []}]},Pattern {value = "B2", elements = [Pattern {value = "B2MID", elements = [Pattern {value = "B2LEAF", elements = []}]}]},Pattern {value = "B3", elements = []}]}
--
-- Type transformation (String to Int):
--
-- >>> elem1 = Pattern { value = "5", elements = [] }
-- >>> elem2 = Pattern { value = "10", elements = [] }
-- >>> pattern = Pattern { value = "20", elements = [elem1, elem2] }
-- >>> fmap (read :: String -> Int) pattern
-- Pattern {value = 20, elements = [Pattern {value = 5, elements = []},Pattern {value = 10, elements = []}]}
--
-- === Edge Cases
--
-- The Functor instance handles all pattern structures correctly:
--
-- **Atomic patterns** (no elements):
--
-- >>> atom = Pattern { value = "atom", elements = [] }
-- >>> fmap (map toUpper) atom
-- Pattern {value = "ATOM", elements = []}
--
-- **Singular patterns** (one element):
--
-- >>> elem = Pattern { value = "elem", elements = [] }
-- >>> pattern = Pattern { value = "singular", elements = [elem] }
-- >>> fmap (map toUpper) pattern
-- Pattern {value = "SINGULAR", elements = [Pattern {value = "ELEM", elements = []}]}
--
-- **Pair patterns** (two elements):
--
-- >>> elem1 = Pattern { value = "first", elements = [] }
-- >>> elem2 = Pattern { value = "second", elements = [] }
-- >>> pattern = Pattern { value = "pair", elements = [elem1, elem2] }
-- >>> fmap (map toUpper) pattern
-- Pattern {value = "PAIR", elements = [Pattern {value = "FIRST", elements = []},Pattern {value = "SECOND", elements = []}]}
--
-- **Extended patterns** (many elements):
--
-- >>> elems = [Pattern { value = "a", elements = [] }, Pattern { value = "b", elements = [] }, Pattern { value = "c", elements = [] }]
-- >>> pattern = Pattern { value = "extended", elements = elems }
-- >>> fmap (map toUpper) pattern
-- Pattern {value = "EXTENDED", elements = [Pattern {value = "A", elements = []},Pattern {value = "B", elements = []},Pattern {value = "C", elements = []}]}
--
-- **Type transformations** (Int to String):
--
-- >>> elem1 = Pattern { value = 5, elements = [] }
-- >>> elem2 = Pattern { value = 10, elements = [] }
-- >>> pattern = Pattern { value = 20, elements = [elem1, elem2] }
-- >>> fmap show pattern
-- Pattern {value = "20", elements = [Pattern {value = "5", elements = []},Pattern {value = "10", elements = []}]}
--
instance Functor Pattern where
  fmap f (Pattern v els) = Pattern (f v) (map (fmap f) els)

-- | Foldable instance for Pattern.
--
-- Enables folding over all values in a pattern structure, including the pattern's
-- own value and all element values at all nesting levels. The Foldable instance
-- provides value aggregation capabilities, allowing developers to compute statistics,
-- combine values, and perform calculations over pattern structures without manually
-- traversing the pattern tree.
--
-- === Value Aggregation
--
-- The Foldable instance processes all values in the pattern structure:
--
-- * The pattern's own value is included in folding operations
-- * All element values are processed recursively
-- * Values from all nesting levels are included
--
-- This enables efficient aggregation operations like summing integers, concatenating
-- strings, counting elements, or computing custom statistics over pattern values.
--
-- === Folding Order
--
-- The @foldr@ operation processes values in right-to-left order:
--
-- * Element values are processed first (right-to-left through the elements list)
-- * The pattern's own value is processed last
--
-- This order ensures that when building data structures or applying operations that
-- depend on processing order, the pattern's own value is combined with the already
-- processed element values.
--
-- === Foldable Laws
--
-- The Foldable instance satisfies standard foldable laws and properties. These laws
-- ensure mathematical correctness and predictable behavior for all foldable operations.
--
-- **Law 1: toList extracts all values**
--
-- For any pattern @p :: Pattern a@, @toList p@ extracts all values from the pattern
-- structure as a flat list. The pattern's own value and all element values at all
-- nesting levels are included exactly once:
--
-- @
-- toList (Pattern v els) = v : concatMap toList els
-- @
--
-- This law ensures that @toList@ processes all values in the pattern structure
-- without duplication or omission.
--
-- **Law 2: foldr processes all values**
--
-- For any pattern @p :: Pattern a@, function @f :: a -> b -> b@, and initial value @z :: b@,
-- @foldr f z p@ processes all values in the pattern structure exactly once:
--
-- @
-- foldr f z (Pattern v els) = f v (foldr (\e acc -> foldr f acc e) z els)
-- @
--
-- This law ensures that @foldr@ processes the pattern's own value and all element
-- values recursively, maintaining right-associative semantics.
--
-- **Law 3: foldl processes all values**
--
-- For any pattern @p :: Pattern a@, function @f :: b -> a -> b@, and initial value @z :: b@,
-- @foldl f z p@ processes all values in the pattern structure exactly once:
--
-- @
-- foldl f z (Pattern v els) = foldl (\acc e -> foldl f acc e) (f z v) els
-- @
--
-- This law ensures that @foldl@ processes the pattern's own value first, then all
-- element values recursively, maintaining left-associative semantics.
--
-- **Law 4: foldMap with monoids**
--
-- For any pattern @p :: Pattern a@, function @f :: a -> m@ where @m@ is a monoid,
-- @foldMap f p@ maps all values to monoids and combines them:
--
-- @
-- foldMap f (Pattern v els) = f v <> foldMap (\e -> foldMap f e) els
-- @
--
-- This law ensures that @foldMap@ processes all values and combines them using
-- monoid operations, enabling efficient aggregation.
--
-- **Law 5: Relationship between toList and foldr**
--
-- For any pattern @p :: Pattern a@, @toList p@ is equivalent to @foldr (:) [] p@:
--
-- @
-- toList p = foldr (:) [] p
-- @
--
-- This law ensures that @toList@ is correctly derived from @foldr@ and extracts
-- all values as a flat list.
--
-- **Law 6: Commutative operations produce same results**
--
-- For any pattern @p :: Pattern a@ and commutative operation @f@, @foldr f z p@
-- and @foldl f z p@ produce the same result:
--
-- @
-- foldr (+) 0 p = foldl (+) 0 p  -- for commutative operations
-- @
--
-- This law ensures that for commutative operations like addition and multiplication,
-- both folding directions produce identical results.
--
-- **Property: Order preservation**
--
-- For any pattern @p :: Pattern a@, multiple calls to @toList p@ produce the same
-- result in the same order:
--
-- @
-- toList p == toList p  -- always true, order is preserved
-- @
--
-- This property ensures that @toList@ is deterministic and preserves the order
-- of values in the pattern structure.
--
-- **Property: All values processed**
--
-- For any pattern @p :: Pattern a@, the number of values in @toList p@ equals the
-- total number of values in the pattern structure (pattern's value plus all element
-- values at all nesting levels):
--
-- @
-- length (toList p) = countValues p
-- @
--
-- where @countValues@ manually counts all values in the pattern structure.
--
-- These laws and properties are verified through property-based testing to ensure
-- mathematical correctness for all pattern structures (atomic, with elements, nested).
--
-- === Examples
--
-- Summing integer values from an atomic pattern:
--
-- >>> atom = Pattern { value = 5, elements = [] }
-- >>> foldr (+) 0 atom
-- 5
--
-- Summing integer values from a pattern with multiple elements:
--
-- >>> elem1 = Pattern { value = 10, elements = [] }
-- >>> elem2 = Pattern { value = 20, elements = [] }
-- >>> pattern = Pattern { value = 100, elements = [elem1, elem2] }
-- >>> foldr (+) 0 pattern
-- 130
--
-- Concatenating string values from a pattern:
--
-- >>> elem1 = Pattern { value = "hello", elements = [] }
-- >>> elem2 = Pattern { value = "world", elements = [] }
-- >>> pattern = Pattern { value = "greeting", elements = [elem1, elem2] }
-- >>> foldr (++) "" pattern
-- "greetinghelloworld"
--
-- Summing values from a nested pattern structure:
--
-- >>> inner = Pattern { value = 1, elements = [] }
-- >>> middle = Pattern { value = 2, elements = [inner] }
-- >>> outer = Pattern { value = 3, elements = [middle] }
-- >>> pattern = Pattern { value = 4, elements = [outer] }
-- >>> foldr (+) 0 pattern
-- 10
--
-- Counting all values in a pattern:
--
-- >>> elem1 = Pattern { value = "a", elements = [] }
-- >>> elem2 = Pattern { value = "b", elements = [] }
-- >>> pattern = Pattern { value = "root", elements = [elem1, elem2] }
-- >>> foldr (\_ acc -> acc + 1) 0 pattern
-- 3
--
-- === Edge Cases
--
-- The Foldable instance handles all pattern structures correctly:
--
-- **Atomic patterns** (no elements):
--
-- >>> atom = Pattern { value = 42, elements = [] }
-- >>> foldr (+) 0 atom
-- 42
-- >>> toList atom
-- [42]
-- >>> foldl (+) 0 atom
-- 42
-- >>> getSum (foldMap Sum atom)
-- 42
--
-- **Patterns with empty elements list**:
--
-- >>> pattern = Pattern { value = 10, elements = [] }
-- >>> foldr (+) 0 pattern
-- 10
-- >>> toList pattern
-- [10]
-- >>> foldl (+) 0 pattern
-- 10
--
-- **Singular patterns** (one element):
--
-- >>> elem = Pattern { value = 5, elements = [] }
-- >>> pattern = Pattern { value = 10, elements = [elem] }
-- >>> foldr (+) 0 pattern
-- 15
-- >>> toList pattern
-- [10, 5]
-- >>> foldl (+) 0 pattern
-- 15
--
-- **Patterns with many elements**:
--
-- >>> elems = map (\i -> Pattern { value = i, elements = [] }) [1..5]
-- >>> pattern = Pattern { value = 100, elements = elems }
-- >>> foldr (+) 0 pattern
-- 115
-- >>> length (toList pattern)
-- 6
-- >>> head (toList pattern)
-- 100
--
-- **Nested patterns** (multiple levels):
--
-- >>> level3 = Pattern { value = 1, elements = [] }
-- >>> level2 = Pattern { value = 2, elements = [level3] }
-- >>> level1 = Pattern { value = 3, elements = [level2] }
-- >>> pattern = Pattern { value = 4, elements = [level1] }
-- >>> foldr (+) 0 pattern
-- 10
-- >>> toList pattern
-- [4, 3, 2, 1]
--
-- **Deep nesting** (3+ levels):
--
-- >>> level4 = Pattern { value = 1, elements = [] }
-- >>> level3 = Pattern { value = 2, elements = [level4] }
-- >>> level2 = Pattern { value = 3, elements = [level3] }
-- >>> level1 = Pattern { value = 4, elements = [level2] }
-- >>> pattern = Pattern { value = 5, elements = [level1] }
-- >>> foldr (+) 0 pattern
-- 15
-- >>> toList pattern
-- [5, 4, 3, 2, 1]
--
-- **Patterns with different value types**:
--
-- String values:
--
-- >>> elem1 = Pattern { value = "hello", elements = [] }
-- >>> elem2 = Pattern { value = "world", elements = [] }
-- >>> pattern = Pattern { value = "greeting", elements = [elem1, elem2] }
-- >>> foldr (++) "" pattern
-- "greetinghelloworld"
-- >>> toList pattern
-- ["greeting", "hello", "world"]
--
-- Integer values:
--
-- >>> elem1 = Pattern { value = 10, elements = [] }
-- >>> elem2 = Pattern { value = 20, elements = [] }
-- >>> pattern = Pattern { value = 100, elements = [elem1, elem2] }
-- >>> foldr (+) 0 pattern
-- 130
-- >>> getSum (foldMap Sum pattern)
-- 130
--
-- **Order preservation**:
--
-- >>> elem1 = Pattern { value = "first", elements = [] }
-- >>> elem2 = Pattern { value = "second", elements = [] }
-- >>> elem3 = Pattern { value = "third", elements = [] }
-- >>> pattern = Pattern { value = "root", elements = [elem1, elem2, elem3] }
-- >>> toList pattern
-- ["root", "first", "second", "third"]
-- >>> foldr (:) [] pattern
-- ["root", "first", "second", "third"]
--
-- **Nested patterns with varying depths**:
--
-- >>> branch1 = Pattern { value = 10, elements = [Pattern { value = 1, elements = [] }] }
-- >>> branch2 = Pattern { value = 20, elements = [Pattern { value = 2, elements = [Pattern { value = 3, elements = [] }] }] }
-- >>> branch3 = Pattern { value = 30, elements = [] }
-- >>> pattern = Pattern { value = 100, elements = [branch1, branch2, branch3] }
-- >>> foldr (+) 0 pattern
-- 166
-- >>> length (toList pattern)
-- 7
--
instance Foldable Pattern where
  -- | Right-associative fold over pattern values.
  --
  -- Processes all values in the pattern structure, including the pattern's own value
  -- and all element values at all nesting levels. Element values are processed first
  -- (right-to-left through the elements list), then the pattern's own value is combined
  -- with the accumulated result.
  --
  -- === Processing Order
  --
  -- The @foldr@ operation processes values in a specific order:
  --
  -- 1. Element values are processed first (right-to-left through the elements list)
  -- 2. The pattern's own value is processed last (combined with accumulated elements)
  --
  -- When building lists with @foldr (:) []@ or using @toList@, this results in the
  -- pattern's own value appearing first in the list, followed by element values in order.
  --
  -- === Examples
  --
  -- Atomic pattern:
  --
  -- >>> atom = Pattern { value = 5, elements = [] }
  -- >>> foldr (+) 0 atom
  -- 5
  --
  -- Pattern with multiple elements (order: elements first, then pattern's value):
  --
  -- >>> elem1 = Pattern { value = 10, elements = [] }
  -- >>> elem2 = Pattern { value = 20, elements = [] }
  -- >>> pattern = Pattern { value = 100, elements = [elem1, elem2] }
  -- >>> foldr (+) 0 pattern
  -- 130
  --
  -- Building a list preserves order (pattern's value first, then elements):
  --
  -- >>> toList pattern
  -- [100, 10, 20]
  --
  -- Nested pattern structure:
  --
  -- >>> inner = Pattern { value = 1, elements = [] }
  -- >>> middle = Pattern { value = 2, elements = [inner] }
  -- >>> pattern = Pattern { value = 3, elements = [middle] }
  -- >>> foldr (+) 0 pattern
  -- 6
  --
  -- Order preservation in nested structures:
  --
  -- >>> toList pattern
  -- [3, 2, 1]
  --
  -- === Right-Associativity
  --
  -- The @foldr@ operation is right-associative, meaning operations are grouped from
  -- right to left. For commutative operations like addition, this produces the same
  -- result as left-associative folding. For non-commutative operations, the order
  -- matters and is preserved as described above.
  --
  -- Example with commutative operation (addition):
  --
  -- >>> elem1 = Pattern { value = 10, elements = [] }
  -- >>> elem2 = Pattern { value = 20, elements = [] }
  -- >>> pattern = Pattern { value = 100, elements = [elem1, elem2] }
  -- >>> foldr (+) 0 pattern
  -- 130
  -- >>> foldr (+) 0 (toList pattern)
  -- 130
  --
  -- Example with non-commutative operation (list building):
  --
  -- >>> elem1 = Pattern { value = "a", elements = [] }
  -- >>> elem2 = Pattern { value = "b", elements = [] }
  -- >>> pattern = Pattern { value = "root", elements = [elem1, elem2] }
  -- >>> toList pattern
  -- ["root", "a", "b"]
  --
  foldr f z (Pattern v els) = f v (foldr (\e acc -> foldr f acc e) z els)
  
  -- | Left-associative fold over pattern values.
  --
  -- Processes all values in the pattern structure, including the pattern's own value
  -- and all element values at all nesting levels. Values are processed in left-to-right
  -- order: the pattern's own value is processed first, then element values are processed
  -- recursively from left to right.
  --
  -- === Processing Order
  --
  -- The @foldl@ operation processes values in a specific order:
  --
  -- 1. The pattern's own value is processed first (combined with initial accumulator)
  -- 2. Element values are processed recursively from left to right
  --
  -- This order ensures that when applying operations that require strict left-to-right
  -- evaluation, the pattern's own value is combined first, followed by element values
  -- in their natural order.
  --
  -- === Examples
  --
  -- Atomic pattern:
  --
  -- >>> atom = Pattern { value = 5, elements = [] }
  -- >>> foldl (+) 0 atom
  -- 5
  --
  -- Pattern with multiple elements (order: pattern's value first, then elements left-to-right):
  --
  -- >>> elem1 = Pattern { value = 10, elements = [] }
  -- >>> elem2 = Pattern { value = 20, elements = [] }
  -- >>> pattern = Pattern { value = 100, elements = [elem1, elem2] }
  -- >>> foldl (+) 0 pattern
  -- 130
  --
  -- Computing running total with left-associative operations:
  --
  -- >>> foldl (-) 0 pattern
  -- -130
  --
  -- Nested pattern structure:
  --
  -- >>> inner = Pattern { value = 1, elements = [] }
  -- >>> middle = Pattern { value = 2, elements = [inner] }
  -- >>> pattern = Pattern { value = 3, elements = [middle] }
  -- >>> foldl (+) 0 pattern
  -- 6
  --
  -- === Left-Associativity
  --
  -- The @foldl@ operation is left-associative, meaning operations are grouped from
  -- left to right. For commutative operations like addition, this produces the same
  -- result as right-associative folding. For non-commutative operations, the order
  -- matters and is preserved as described above.
  --
  -- Example with commutative operation (addition):
  --
  -- >>> elem1 = Pattern { value = 10, elements = [] }
  -- >>> elem2 = Pattern { value = 20, elements = [] }
  -- >>> pattern = Pattern { value = 100, elements = [elem1, elem2] }
  -- >>> foldl (+) 0 pattern
  -- 130
  -- >>> foldl (+) 0 (toList pattern)
  -- 130
  --
  -- Example with non-commutative operation (subtraction):
  --
  -- >>> elem1 = Pattern { value = 5, elements = [] }
  -- >>> elem2 = Pattern { value = 3, elements = [] }
  -- >>> pattern = Pattern { value = 10, elements = [elem1, elem2] }
  -- >>> foldl (-) 0 pattern
  -- -18
  --
  foldl f z (Pattern v els) = Prelude.foldl (\acc e -> foldl f acc e) (f z v) els
  
  -- | Map values to monoids and combine them efficiently.
  --
  -- Maps each value in the pattern structure to a monoid and combines them
  -- using monoid operations. This provides a declarative approach for common
  -- aggregation patterns like summing, concatenating, or counting without
  -- explicitly writing fold functions.
  --
  -- The @foldMap@ operation processes all values in the pattern structure,
  -- including the pattern's own value and all element values at all nesting
  -- levels. Values are mapped to monoids and combined using the monoid's
  -- @mappend@ operation (or @<>@).
  --
  -- === Examples
  --
  -- Summing integer values with Sum monoid:
  --
  -- >>> elem1 = Pattern { value = 10, elements = [] }
  -- >>> elem2 = Pattern { value = 20, elements = [] }
  -- >>> pattern = Pattern { value = 100, elements = [elem1, elem2] }
  -- >>> getSum (foldMap Sum pattern)
  -- 130
  --
  -- Concatenating string values with list monoid:
  --
  -- >>> elem1 = Pattern { value = "hello", elements = [] }
  -- >>> elem2 = Pattern { value = "world", elements = [] }
  -- >>> pattern = Pattern { value = "greeting", elements = [elem1, elem2] }
  -- >>> foldMap (: []) pattern
  -- ["greeting", "hello", "world"]
  --
  -- Logical AND with All monoid:
  --
  -- >>> elem1 = Pattern { value = True, elements = [] }
  -- >>> elem2 = Pattern { value = True, elements = [] }
  -- >>> pattern = Pattern { value = True, elements = [elem1, elem2] }
  -- >>> getAll (foldMap All pattern)
  -- True
  --
  -- Nested pattern structure:
  --
  -- >>> inner = Pattern { value = 1, elements = [] }
  -- >>> middle = Pattern { value = 2, elements = [inner] }
  -- >>> pattern = Pattern { value = 3, elements = [middle] }
  -- >>> getSum (foldMap Sum pattern)
  -- 6
  --
  -- === Monoid Operations
  --
  -- The @foldMap@ operation uses monoid operations to combine mapped values:
  --
  -- * @Sum@ monoid: Addition for numeric values
  -- * @Product@ monoid: Multiplication for numeric values
  -- * @All@ monoid: Logical AND for boolean values
  -- * @Any@ monoid: Logical OR for boolean values
  -- * List monoid: Concatenation for lists
  -- * Custom monoids: Any type with a Monoid instance
  --
  -- === Efficiency
  --
  -- The @foldMap@ operation is implemented efficiently using the pattern's
  -- @foldr@ implementation. For monoids that support efficient combination,
  -- this provides optimal performance for aggregation operations.
  --
  -- Example with Sum monoid (efficient):
  --
  -- >>> getSum (foldMap Sum (Pattern { value = 5, elements = [] }))
  -- 5
  --
  -- Example with list monoid (efficient concatenation):
  --
  -- >>> foldMap (: []) (Pattern { value = "test", elements = [] })
  -- ["test"]
  --
  -- Note: @foldMap@ is automatically derived from @foldr@ and works correctly
  -- for all pattern structures. The default implementation processes all values
  -- in the pattern structure, including the pattern's own value and all element
  -- values at all nesting levels.
  
  -- Note: @toList@ is automatically derived from @foldr@ and extracts all values
  -- as a flat list. The pattern's own value and all element values at all
  -- nesting levels are included in the result.

-- | Traversable instance for Pattern.
--
-- Enables effectful traversal over all values in a pattern structure while
-- preserving pattern structure (element count, nesting depth, element order).
-- The Traversable instance provides the @traverse@ operation that applies
-- effectful functions to all values in the pattern structure, combining effects
-- using applicative semantics.
--
-- === Effectful Traversal
--
-- The Traversable instance processes all values in the pattern structure:
--
-- * The pattern's own value is processed first
-- * All element values are processed recursively
-- * Values from all nesting levels are included
-- * Effects are combined using applicative semantics
--
-- This enables operations like validation, state threading, IO operations, and
-- error handling over pattern values while maintaining pattern structure.
--
-- === Structure Preservation
--
-- The Traversable instance preserves pattern structure during traversal:
--
-- * Element count: The number of elements remains unchanged
-- * Nesting depth: The nesting structure is preserved
-- * Element order: The order of elements is maintained
--
-- Only the values are transformed; the pattern structure itself remains identical.
--
-- === Effect Combination
--
-- Effects are combined using standard applicative semantics for each applicative functor:
--
-- * **Maybe**: Short-circuits to Nothing if any value produces Nothing
-- * **Either**: Short-circuits to Left with first error if any value produces Left
-- * **[]**: Collects all results from all values
-- * **Identity**: Preserves structure without effects
-- * **IO**: Performs all IO operations and combines results
-- * **State**: Threads state through all values
--
-- === Traversable Laws
--
-- The Traversable instance satisfies the standard traversable laws, which are verified
-- through property-based testing in the test suite:
--
-- **Naturality Law**: For any applicative transformation @t@ and function @f@,
--
-- @
-- t . traverse f = traverse (t . f)
-- @
--
-- This law ensures that applicative transformations commute with traversal.
--
-- **Identity Law**: For all patterns @p :: Pattern a@,
--
-- @
-- traverse Identity p = Identity p
-- @
--
-- This law states that traversing with the Identity applicative functor produces
-- the same pattern wrapped in Identity.
--
-- **Composition Law**: For all patterns @p :: Pattern a@ and functions @f@ and @g@,
--
-- @
-- traverse (Compose . fmap g . f) p = Compose . fmap (traverse g) . traverse f $ p
-- @
--
-- This law ensures that composition of traversals equals sequential traversal.
--
-- All laws hold for all pattern structures (atomic, with elements, nested) and all
-- value types, as verified by property-based tests.
--
-- === Examples
--
-- Traversing atomic pattern with Identity (no effects):
--
-- >>> atom = Pattern { value = "test", elements = [] }
-- >>> traverse Identity atom
-- Identity (Pattern {value = "test", elements = []})
--
-- Traversing atomic pattern with Maybe (validation):
--
-- >>> let validate x = if x > 0 then Just x else Nothing
-- >>> traverse validate (Pattern { value = 5, elements = [] })
-- Just (Pattern {value = 5, elements = []})
--
-- >>> traverse validate (Pattern { value = -3, elements = [] })
-- Nothing
--
-- Traversing atomic pattern with Either (error handling):
--
-- >>> let validate x = if x > 0 then Right x else Left ("Invalid: " ++ show x)
-- >>> traverse validate (Pattern { value = 5, elements = [] })
-- Right (Pattern {value = 5, elements = []})
--
-- >>> traverse validate (Pattern { value = -3, elements = [] })
-- Left "Invalid: -3"
--
-- Traversing pattern with multiple elements:
--
-- >>> let validate x = if x > 0 then Just x else Nothing
-- >>> elem1 = Pattern { value = 5, elements = [] }
-- >>> elem2 = Pattern { value = 10, elements = [] }
-- >>> pattern = Pattern { value = 20, elements = [elem1, elem2] }
-- >>> traverse validate pattern
-- Just (Pattern {value = 20, elements = [Pattern {value = 5, elements = []},Pattern {value = 10, elements = []}]})
--
-- Traversing nested pattern structure:
--
-- >>> let validate x = if x > 0 then Just x else Nothing
-- >>> inner = Pattern { value = 1, elements = [] }
-- >>> middle = Pattern { value = 2, elements = [inner] }
-- >>> outer = Pattern { value = 3, elements = [middle] }
-- >>> pattern = Pattern { value = 4, elements = [outer] }
-- >>> traverse validate pattern
-- Just (Pattern {value = 4, elements = [Pattern {value = 3, elements = [Pattern {value = 2, elements = [Pattern {value = 1, elements = []}]}]}]})
--
-- === Edge Cases
--
-- The Traversable instance handles all pattern structures correctly:
--
-- **Atomic patterns** (no elements):
--
-- >>> traverse Identity (Pattern { value = "atom", elements = [] })
-- Identity (Pattern {value = "atom", elements = []})
--
-- **Singular patterns** (one element):
--
-- >>> elem = Pattern { value = "elem", elements = [] }
-- >>> pattern = Pattern { value = "singular", elements = [elem] }
-- >>> traverse Identity pattern
-- Identity (Pattern {value = "singular", elements = [Pattern {value = "elem", elements = []}]})
--
-- **Patterns with many elements**:
--
-- >>> elems = [Pattern { value = "a", elements = [] }, Pattern { value = "b", elements = [] }]
-- >>> pattern = Pattern { value = "root", elements = elems }
-- >>> traverse Identity pattern
-- Identity (Pattern {value = "root", elements = [Pattern {value = "a", elements = []},Pattern {value = "b", elements = []}]})
--
-- **Deep nesting** (3+ levels):
--
-- >>> level3 = Pattern { value = "level3", elements = [] }
-- >>> level2 = Pattern { value = "level2", elements = [level3] }
-- >>> level1 = Pattern { value = "level1", elements = [level2] }
-- >>> pattern = Pattern { value = "root", elements = [level1] }
-- >>> traverse Identity pattern
-- Identity (Pattern {value = "root", elements = [Pattern {value = "level1", elements = [Pattern {value = "level2", elements = [Pattern {value = "level3", elements = []}]}]}]})
--
-- === Validation Use Cases
--
-- The Traversable instance enables validation of pattern values using Maybe or Either
-- applicative functors. Validation functions can check values and return success or
-- failure, with effects combined using applicative semantics.
--
-- **Validation with Maybe** (simple success/failure):
--
-- >>> let validate x = if x > 0 then Just x else Nothing
-- >>> elem1 = Pattern { value = 5, elements = [] }
-- >>> elem2 = Pattern { value = 10, elements = [] }
-- >>> pattern = Pattern { value = 20, elements = [elem1, elem2] }
-- >>> traverse validate pattern
-- Just (Pattern {value = 20, elements = [Pattern {value = 5, elements = []},Pattern {value = 10, elements = []}]})
--
-- >>> let validate x = if x > 0 then Just x else Nothing
-- >>> elem1 = Pattern { value = 5, elements = [] }
-- >>> elem2 = Pattern { value = -3, elements = [] }
-- >>> pattern = Pattern { value = 20, elements = [elem1, elem2] }
-- >>> traverse validate pattern
-- Nothing
--
-- **Validation with Either** (success with error messages):
--
-- >>> let validate x = if x > 0 then Right x else Left ("Invalid: " ++ show x)
-- >>> elem1 = Pattern { value = 5, elements = [] }
-- >>> elem2 = Pattern { value = 10, elements = [] }
-- >>> pattern = Pattern { value = 20, elements = [elem1, elem2] }
-- >>> traverse validate pattern
-- Right (Pattern {value = 20, elements = [Pattern {value = 5, elements = []},Pattern {value = 10, elements = []}]})
--
-- >>> let validate x = if x > 0 then Right x else Left ("Invalid: " ++ show x)
-- >>> elem1 = Pattern { value = 5, elements = [] }
-- >>> elem2 = Pattern { value = -3, elements = [] }
-- >>> pattern = Pattern { value = 20, elements = [elem1, elem2] }
-- >>> traverse validate pattern
-- Left "Invalid: -3"
--
-- **Validation on nested patterns**:
--
-- >>> let validate x = if x > 0 then Just x else Nothing
-- >>> inner = Pattern { value = 1, elements = [] }
-- >>> middle = Pattern { value = 2, elements = [inner] }
-- >>> outer = Pattern { value = 3, elements = [middle] }
-- >>> pattern = Pattern { value = 4, elements = [outer] }
-- >>> traverse validate pattern
-- Just (Pattern {value = 4, elements = [Pattern {value = 3, elements = [Pattern {value = 2, elements = [Pattern {value = 1, elements = []}]}]}]})
--
-- >>> let validate x = if x > 0 then Just x else Nothing
-- >>> inner = Pattern { value = -1, elements = [] }
-- >>> middle = Pattern { value = 2, elements = [inner] }
-- >>> outer = Pattern { value = 3, elements = [middle] }
-- >>> pattern = Pattern { value = 4, elements = [outer] }
-- >>> traverse validate pattern
-- Nothing
--
-- === Error Handling Patterns
--
-- The Traversable instance supports two error handling patterns:
--
-- **Maybe pattern**: Use when you only need to know if validation succeeded or failed.
-- Short-circuits to Nothing on first failure. Useful for simple validation where error
-- messages are not needed.
--
-- **Either pattern**: Use when you need error messages explaining why validation failed.
-- Short-circuits to Left with first error encountered. Useful for validation where
-- detailed error reporting is required.
--
-- Both patterns ensure that validation fails if any value at any nesting level is invalid,
-- providing comprehensive validation coverage for entire pattern structures.
--
instance Traversable Pattern where
  -- | Effectful traversal over pattern values.
  --
  -- Applies an effectful function to all values in the pattern structure while
  -- preserving pattern structure. The function is applied to the pattern's own
  -- value first, then recursively to all element values at all nesting levels.
  -- Effects are combined using applicative semantics.
  --
  -- === Processing Order
  --
  -- The @traverse@ operation processes values in a specific order:
  --
  -- 1. The pattern's own value is processed first
  -- 2. Element values are processed recursively from left to right
  --
  -- This order ensures that when building data structures or applying operations
  -- that depend on processing order, the pattern's own value is processed first,
  -- followed by element values in their natural order.
  --
  -- === Examples
  --
  -- Atomic pattern:
  --
  -- >>> traverse Identity (Pattern { value = 5, elements = [] })
  -- Identity (Pattern {value = 5, elements = []})
  --
  -- Pattern with multiple elements:
  --
  -- >>> let validate x = if x > 0 then Just x else Nothing
  -- >>> elem1 = Pattern { value = 5, elements = [] }
  -- >>> elem2 = Pattern { value = 10, elements = [] }
  -- >>> pattern = Pattern { value = 20, elements = [elem1, elem2] }
  -- >>> traverse validate pattern
  -- Just (Pattern {value = 20, elements = [Pattern {value = 5, elements = []},Pattern {value = 10, elements = []}]})
  --
  -- Nested pattern structure:
  --
  -- >>> let validate x = if x > 0 then Just x else Nothing
  -- >>> inner = Pattern { value = 1, elements = [] }
  -- >>> middle = Pattern { value = 2, elements = [inner] }
  -- >>> pattern = Pattern { value = 3, elements = [middle] }
  -- >>> traverse validate pattern
  -- Just (Pattern {value = 3, elements = [Pattern {value = 2, elements = [Pattern {value = 1, elements = []}]}]})
  --
  traverse f (Pattern v els) = 
    Pattern <$> f v <*> traverse (traverse f) els
  
  -- | Sequence applicative effects from a pattern.
  --
  -- Converts a pattern containing applicative values into an applicative
  -- value containing a pattern. Effects are combined using applicative semantics.
  -- This is equivalent to @traverse id@.
  --
  -- === Effect Sequencing
  --
  -- The @sequenceA@ operation processes all values in the pattern structure:
  --
  -- * The pattern's own value is processed first
  -- * All element values are processed recursively
  -- * Values from all nesting levels are included
  -- * Effects are combined using applicative semantics
  --
  -- This enables collecting effects from pattern values and working with
  -- effectful patterns in a structured way.
  --
  -- === Structure Preservation
  --
  -- The @sequenceA@ operation preserves pattern structure during sequencing:
  --
  -- * Element count: The number of elements remains unchanged
  -- * Nesting depth: The nesting structure is preserved
  -- * Element order: The order of elements is maintained
  --
  -- Only the values are unwrapped from their applicative contexts; the pattern
  -- structure itself remains identical.
  --
  -- === Effect Combination
  --
  -- Effects are combined using standard applicative semantics for each applicative functor:
  --
  -- * **Maybe**: Returns Just pattern if all values are Just, Nothing otherwise (short-circuits on first Nothing)
  -- * **Either**: Returns Right pattern if all values are Right, Left with first error otherwise (short-circuits on first Left)
  -- * **[]**: Collects all combinations of values
  -- * **Identity**: Unwraps Identity values
  -- * **IO**: Performs all IO operations and combines results
  -- * **State**: Threads state through all values
  --
  -- === Relationship to traverse
  --
  -- The @sequenceA@ operation is equivalent to @traverse id@:
  --
  -- @
  -- sequenceA = traverse id
  -- @
  --
  -- This relationship ensures that sequencing effects is consistent with
  -- effectful traversal operations.
  --
  -- === Examples
  --
  -- Sequencing pattern containing Identity values:
  --
  -- >>> atom = Pattern { value = Identity "test", elements = [] }
  -- >>> sequenceA atom
  -- Identity (Pattern {value = "test", elements = []})
  --
  -- Sequencing pattern containing Maybe values (all Just):
  --
  -- >>> elem1 = Pattern { value = Just 5, elements = [] }
  -- >>> elem2 = Pattern { value = Just 10, elements = [] }
  -- >>> pattern = Pattern { value = Just 20, elements = [elem1, elem2] }
  -- >>> sequenceA pattern
  -- Just (Pattern {value = 20, elements = [Pattern {value = 5, elements = []},Pattern {value = 10, elements = []}]})
  --
  -- Sequencing pattern containing Maybe values (one Nothing):
  --
  -- >>> elem1 = Pattern { value = Just 5, elements = [] }
  -- >>> elem2 = Pattern { value = Nothing, elements = [] }
  -- >>> pattern = Pattern { value = Just 20, elements = [elem1, elem2] }
  -- >>> sequenceA pattern
  -- Nothing
  --
  -- Sequencing pattern containing Either values (all Right):
  --
  -- >>> elem1 = Pattern { value = Right 5, elements = [] }
  -- >>> elem2 = Pattern { value = Right 10, elements = [] }
  -- >>> pattern = Pattern { value = Right 20, elements = [elem1, elem2] }
  -- >>> sequenceA pattern
  -- Right (Pattern {value = 20, elements = [Pattern {value = 5, elements = []},Pattern {value = 10, elements = []}]})
  --
  -- Sequencing pattern containing Either values (one Left):
  --
  -- >>> elem1 = Pattern { value = Right 5, elements = [] }
  -- >>> elem2 = Pattern { value = Left "error", elements = [] }
  -- >>> pattern = Pattern { value = Right 20, elements = [elem1, elem2] }
  -- >>> sequenceA pattern
  -- Left "error"
  --
  -- Sequencing nested pattern structure:
  --
  -- >>> inner = Pattern { value = Just 1, elements = [] }
  -- >>> middle = Pattern { value = Just 2, elements = [inner] }
  -- >>> outer = Pattern { value = Just 3, elements = [middle] }
  -- >>> pattern = Pattern { value = Just 4, elements = [outer] }
  -- >>> sequenceA pattern
  -- Just (Pattern {value = 4, elements = [Pattern {value = 3, elements = [Pattern {value = 2, elements = [Pattern {value = 1, elements = []}]}]}]})
  --
  -- === Edge Cases
  --
  -- The @sequenceA@ operation handles all pattern structures correctly:
  --
  -- **Atomic patterns** (no elements):
  --
  -- >>> sequenceA (Pattern { value = Just 5, elements = [] })
  -- Just (Pattern {value = 5, elements = []})
  --
  -- **Singular patterns** (one element):
  --
  -- >>> elem = Pattern { value = Just 5, elements = [] }
  -- >>> pattern = Pattern { value = Just 10, elements = [elem] }
  -- >>> sequenceA pattern
  -- Just (Pattern {value = 10, elements = [Pattern {value = 5, elements = []}]})
  --
  -- **Patterns with many elements**:
  --
  -- >>> elems = [Pattern { value = Just 1, elements = [] }, Pattern { value = Just 2, elements = [] }]
  -- >>> pattern = Pattern { value = Just 100, elements = elems }
  -- >>> sequenceA pattern
  -- Just (Pattern {value = 100, elements = [Pattern {value = 1, elements = []},Pattern {value = 2, elements = []}]})
  --
  -- **Deep nesting** (3+ levels):
  --
  -- >>> level3 = Pattern { value = Just 1, elements = [] }
  -- >>> level2 = Pattern { value = Just 2, elements = [level3] }
  -- >>> level1 = Pattern { value = Just 3, elements = [level2] }
  -- >>> pattern = Pattern { value = Just 4, elements = [level1] }
  -- >>> sequenceA pattern
  -- Just (Pattern {value = 4, elements = [Pattern {value = 3, elements = [Pattern {value = 2, elements = [Pattern {value = 1, elements = []}]}]}]})
  --
  sequenceA = traverse id

-- | Create an atomic pattern (pattern with no elements) from a value.
--
-- This function provides a convenient way to create atomic patterns without
-- using verbose record syntax. The resulting pattern is functionally identical
-- to one created with @Pattern { value = x, elements = [] }@.
--
-- === Examples
--
-- Create an atomic pattern with a string value:
--
-- >>> atom = pattern "atom1"
-- >>> value atom
-- "atom1"
-- >>> elements atom
-- []
--
-- Create an atomic pattern with an integer value:
--
-- >>> num = pattern 42
-- >>> value num
-- 42
--
-- Create an atomic pattern with a custom type:
--
-- >>> data Person = Person { name :: String, age :: Maybe Int }
-- >>> person = pattern (Person "Alice" (Just 30))
-- >>> value person
-- Person {name = "Alice", age = Just 30}
--
-- === Functional Equivalence
--
-- The following are equivalent:
--
-- >>> pattern "test" == Pattern { value = "test", elements = [] }
-- True
pattern :: v -> Pattern v
pattern v = Pattern { value = v, elements = [] }

-- | Create a pattern with elements from a value and a list of pattern elements.
--
-- This function provides a convenient way to create patterns with elements
-- without using verbose record syntax. The resulting pattern is functionally
-- identical to one created with @Pattern { value = x, elements = ps }@.
--
-- The function preserves the order of elements in the input list and handles
-- all element counts: 0 (atomic pattern), 1 (singular pattern), 2 (pair),
-- or many (extended pattern).
--
-- === Examples
--
-- Create a singular pattern (one element):
--
-- >>> singular = patternWith "soccer" [pattern "a team sport involving kicking a ball"]
-- >>> length (elements singular)
-- 1
--
-- Create a pair pattern (two elements):
--
-- >>> pair = patternWith "knows" [pattern "Alice", pattern "Bob"]
-- >>> length (elements pair)
-- 2
--
-- Create an extended pattern (many elements):
--
-- >>> extended = patternWith "graph" [pattern "elem1", pattern "elem2", pattern "elem3"]
-- >>> length (elements extended)
-- 3
--
-- Empty list produces atomic pattern:
--
-- >>> atomic = patternWith "empty" []
-- >>> elements atomic
-- []
-- >>> atomic == pattern "empty"
-- True
--
-- === Functional Equivalence
--
-- The following are equivalent:
--
-- >>> patternWith "test" [pattern "elem"] == Pattern { value = "test", elements = [Pattern { value = "elem", elements = [] }] }
-- True
--
-- === Element Order
--
-- Element order is preserved:
--
-- >>> p1 = patternWith "seq" [pattern "a", pattern "b"]
-- >>> p2 = patternWith "seq" [pattern "b", pattern "a"]
-- >>> p1 == p2
-- False
patternWith :: v -> [Pattern v] -> Pattern v
patternWith v ps = Pattern { value = v, elements = ps }

-- | Create a pattern from a list of values by converting each value to an atomic pattern.
--
-- This function provides a convenient way to create patterns from lists of raw values.
-- Each value in the list is automatically converted to an atomic pattern, then all
-- atomic patterns are combined into a single pattern with the given decoration.
--
-- The function preserves the order of values in the input list and handles all
-- element counts: 0 (atomic pattern), 1 (singular pattern), 2 (pair), or many
-- (extended pattern).
--
-- === Examples
--
-- Create a pattern from a list of strings:
--
-- >>> p = fromList "graph" ["Alice", "Bob", "Charlie"]
-- >>> value p
-- "graph"
-- >>> length (elements p)
-- 3
-- >>> map value (elements p)
-- ["Alice","Bob","Charlie"]
--
-- Create a pattern from a list of integers:
--
-- >>> nums = fromList "numbers" [1, 2, 3, 4, 5]
-- >>> length (elements nums)
-- 5
--
-- Empty list produces atomic pattern:
--
-- >>> atomic = fromList "empty" []
-- >>> elements atomic
-- []
-- >>> atomic == pattern "empty"
-- True
--
-- === Functional Equivalence
--
-- The following are equivalent:
--
-- >>> fromList "test" ["a", "b"] == patternWith "test" [pattern "a", pattern "b"]
-- True
--
-- === Implementation
--
-- This function is implemented as:
--
-- @
-- fromList decoration values = patternWith decoration (map pattern values)
-- @
fromList :: v -> [v] -> Pattern v
fromList decoration values = patternWith decoration (map pattern values)

-- | Extract a pattern as a tuple preserving its structure.
--
-- Returns a tuple @(v, [Pattern v])@ where the first element is the pattern's
-- value and the second element is the list of element patterns. This function
-- preserves the pattern's structure by keeping elements as Pattern values
-- rather than flattening them.
--
-- The tuple representation directly reflects the Pattern's structure:
-- the value (decoration) and the list of pattern elements. This enables
-- structure-preserving operations and makes the pattern's composition explicit.
--
-- === Examples
--
-- Atomic pattern (no elements):
--
-- >>> atom = Pattern { value = "test", elements = [] }
-- >>> toTuple atom
-- ("test", [])
--
-- Pattern with multiple elements:
--
-- >>> elem1 = Pattern { value = "a", elements = [] }
-- >>> elem2 = Pattern { value = "b", elements = [] }
-- >>> pattern = Pattern { value = "root", elements = [elem1, elem2] }
-- >>> toTuple pattern
-- ("root", [Pattern {value = "a", elements = []},Pattern {value = "b", elements = []}])
--
-- Nested pattern structure:
--
-- >>> inner = Pattern { value = "inner", elements = [] }
-- >>> middle = Pattern { value = "middle", elements = [inner] }
-- >>> pattern = Pattern { value = "root", elements = [middle] }
-- >>> toTuple pattern
-- ("root", [Pattern {value = "middle", elements = [Pattern {value = "inner", elements = []}]}])
--
-- Pattern with integer values:
--
-- >>> elem1 = Pattern { value = 10, elements = [] }
-- >>> elem2 = Pattern { value = 20, elements = [] }
-- >>> pattern = Pattern { value = 100, elements = [elem1, elem2] }
-- >>> toTuple pattern
-- (100, [Pattern {value = 10, elements = []},Pattern {value = 20, elements = []}])
--
-- === Structure Preservation
--
-- The @toTuple@ function preserves the pattern's structure:
--
-- * Elements remain as Pattern values (not flattened to their values)
-- * Nested structures are preserved in the elements list
-- * The pattern's value and elements are accessible separately
--
-- This is different from @toList@ which flattens all values into a single list.
-- Use @toTuple@ when you need to work with the pattern's value and elements
-- separately while maintaining the structural relationship.
--
-- === Edge Cases
--
-- **Atomic patterns** (no elements):
--
-- >>> atom = Pattern { value = "atom", elements = [] }
-- >>> toTuple atom
-- ("atom", [])
--
-- **Singular patterns** (one element):
--
-- >>> elem = Pattern { value = "elem", elements = [] }
-- >>> pattern = Pattern { value = "singular", elements = [elem] }
-- >>> toTuple pattern
-- ("singular", [Pattern {value = "elem", elements = []}])
--
-- **Patterns with many elements**:
--
-- >>> elems = [Pattern { value = "a", elements = [] }, Pattern { value = "b", elements = [] }, Pattern { value = "c", elements = [] }]
-- >>> pattern = Pattern { value = "root", elements = elems }
-- >>> toTuple pattern
-- ("root", [Pattern {value = "a", elements = []},Pattern {value = "b", elements = []},Pattern {value = "c", elements = []}])
--
toTuple :: Pattern v -> (v, [Pattern v])
toTuple (Pattern v els) = (v, els)

-- | Extract all values from a pattern as a flat list, explicitly flattening all nesting levels.
--
-- This function extracts all values from the pattern structure, including the pattern's own value
-- and all element values at all nesting levels, into a single flat list. The function is equivalent
-- to @toList@ (standard Foldable behavior) but is provided explicitly for clarity and to make
-- flattening operations intentional.
--
-- The @flatten@ function processes all values in the pattern structure:
--
-- * The pattern's own value is included in the result
-- * All element values are processed recursively
-- * Values from all nesting levels are included
-- * The result is always a flat list (no nested lists)
--
-- === Relationship to toList
--
-- The @flatten@ function is equivalent to @toList@ (standard Foldable behavior):
--
-- @
-- flatten p = toList p
-- @
--
-- Both functions extract all values as a flat list. Use @flatten@ when you want to make the
-- flattening operation explicit, or use @toList@ for standard Foldable behavior.
--
-- === Examples
--
-- Atomic pattern:
--
-- >>> atom = Pattern { value = "test", elements = [] }
-- >>> flatten atom
-- ["test"]
--
-- Pattern with multiple elements:
--
-- >>> elem1 = Pattern { value = "a", elements = [] }
-- >>> elem2 = Pattern { value = "b", elements = [] }
-- >>> pattern = Pattern { value = "root", elements = [elem1, elem2] }
-- >>> flatten pattern
-- ["root", "a", "b"]
--
-- Nested pattern structure:
--
-- >>> inner = Pattern { value = "inner", elements = [] }
-- >>> middle = Pattern { value = "middle", elements = [inner] }
-- >>> pattern = Pattern { value = "root", elements = [middle] }
-- >>> flatten pattern
-- ["root", "middle", "inner"]
--
-- Pattern with integer values:
--
-- >>> elem1 = Pattern { value = 10, elements = [] }
-- >>> elem2 = Pattern { value = 20, elements = [] }
-- >>> pattern = Pattern { value = 100, elements = [elem1, elem2] }
-- >>> flatten pattern
-- [100, 10, 20]
--
-- Using flatten for aggregation:
--
-- >>> pattern = Pattern { value = 10, elements = [Pattern { value = 5, elements = [] }, Pattern { value = 3, elements = [] }] }
-- >>> sum (flatten pattern)
-- 18
--
-- === Edge Cases
--
-- **Atomic patterns** (no elements):
--
-- >>> atom = Pattern { value = 42, elements = [] }
-- >>> flatten atom
-- [42]
--
-- **Patterns with empty elements list**:
--
-- >>> pattern = Pattern { value = 10, elements = [] }
-- >>> flatten pattern
-- [10]
--
-- **Singular patterns** (one element):
--
-- >>> elem = Pattern { value = 5, elements = [] }
-- >>> pattern = Pattern { value = 10, elements = [elem] }
-- >>> flatten pattern
-- [10, 5]
--
-- **Patterns with many elements**:
--
-- >>> elems = map (\i -> Pattern { value = i, elements = [] }) [1..5]
-- >>> pattern = Pattern { value = 100, elements = elems }
-- >>> flatten pattern
-- [100, 1, 2, 3, 4, 5]
--
-- **Deep nesting** (3+ levels):
--
-- >>> level4 = Pattern { value = 1, elements = [] }
-- >>> level3 = Pattern { value = 2, elements = [level4] }
-- >>> level2 = Pattern { value = 3, elements = [level3] }
-- >>> level1 = Pattern { value = 4, elements = [level2] }
-- >>> pattern = Pattern { value = 5, elements = [level1] }
-- >>> flatten pattern
-- [5, 4, 3, 2, 1]
--
flatten :: Pattern a -> [a]
flatten = toList

-- | Query the number of direct elements in a pattern's sequence.
--
-- Returns the count of direct child elements in the pattern's sequence.
-- This function provides the most basic structural information about a pattern,
-- indicating how many elements are directly contained in the pattern's sequence.
--
-- The @length@ function counts only direct children, not nested descendants.
-- For example, a pattern with one element that itself contains elements will
-- have @length@ of 1, not the total count of all nested elements.
--
-- === Relationship to elements
--
-- The @length@ function is equivalent to @length (elements p)@:
--
-- @
-- length p = length (elements p)
-- @
--
-- This provides a convenient way to query element count without explicitly
-- accessing the @elements@ field.
--
-- === Examples
--
-- Atomic pattern (no elements):
--
-- >>> atom = Pattern { value = "atom", elements = [] }
-- >>> length atom
-- 0
--
-- Singular pattern (one element):
--
-- >>> elem = Pattern { value = "elem", elements = [] }
-- >>> pattern = Pattern { value = "pattern", elements = [elem] }
-- >>> length pattern
-- 1
--
-- Pattern with multiple elements:
--
-- >>> elem1 = Pattern { value = "e1", elements = [] }
-- >>> elem2 = Pattern { value = "e2", elements = [] }
-- >>> elem3 = Pattern { value = "e3", elements = [] }
-- >>> pattern = Pattern { value = "pattern", elements = [elem1, elem2, elem3] }
-- >>> length pattern
-- 3
--
-- Nested pattern (counts only direct children):
--
-- >>> inner = Pattern { value = "inner", elements = [] }
-- >>> middle = Pattern { value = "middle", elements = [inner] }
-- >>> outer = Pattern { value = "outer", elements = [middle] }
-- >>> pattern = Pattern { value = "root", elements = [outer] }
-- >>> length pattern
-- 1
-- >>> length outer
-- 1
-- >>> length middle
-- 1
-- >>> length inner
-- 0
--
-- === Edge Cases
--
-- **Atomic patterns** (no elements):
--
-- >>> length (Pattern { value = "atom", elements = [] })
-- 0
--
-- **Patterns with empty elements list**:
--
-- >>> length (Pattern { value = "empty", elements = [] })
-- 0
--
-- **Patterns with many elements**:
--
-- >>> elems = map (\i -> Pattern { value = i, elements = [] }) [1..10]
-- >>> pattern = Pattern { value = 100, elements = elems }
-- >>> length pattern
-- 10
--
-- === Performance
--
-- The @length@ function completes in O(1) time for patterns with elements
-- stored as lists, as it simply returns the length of the elements list.
-- Performance is constant regardless of pattern structure or nesting depth.
--
-- === Type Safety
--
-- The @length@ function works with patterns of any value type @v@:
--
-- >>> length (Pattern { value = "test", elements = [] } :: Pattern String)
-- 0
-- >>> length (Pattern { value = 42, elements = [] } :: Pattern Int)
-- 0
--
length :: Pattern v -> Int
length (Pattern _ els) = Prelude.length els

-- | Query the total number of nodes in a pattern structure.
--
-- Returns the total count of all nodes in the pattern structure, including
-- the pattern itself and all nested patterns at all levels. This provides a
-- complete picture of pattern complexity by counting every node in the
-- recursive structure.
--
-- The @size@ function counts all nodes recursively:
--
-- * The pattern itself counts as 1 node
-- * Each element pattern is counted recursively
-- * All nested patterns at all levels are included
--
-- This is different from @length@, which counts only direct children.
-- The @size@ function provides the total node count across the entire
-- pattern structure.
--
-- === Relationship to length
--
-- The @size@ function is always greater than or equal to @length@:
--
-- @
-- size p >= length p
-- @
--
-- This is because @size@ counts the root node plus all descendants, while
-- @length@ counts only direct children.
--
-- === Recursive Definition
--
-- The @size@ function is defined recursively:
--
-- @
-- size p = 1 + sum (map size (elements p))
-- @
--
-- This means:
-- * The pattern itself contributes 1 node
-- * Each element's size is computed recursively
-- * The sum of all element sizes is added to 1
--
-- === Examples
--
-- Atomic pattern (single node):
--
-- >>> atom = Pattern { value = "atom", elements = [] }
-- >>> size atom
-- 1
--
-- Pattern with direct elements (no nesting):
--
-- >>> elem1 = Pattern { value = "e1", elements = [] }
-- >>> elem2 = Pattern { value = "e2", elements = [] }
-- >>> elem3 = Pattern { value = "e3", elements = [] }
-- >>> pattern = Pattern { value = "pattern", elements = [elem1, elem2, elem3] }
-- >>> size pattern
-- 4
--
-- Deeply nested pattern:
--
-- >>> level4 = Pattern { value = "level4", elements = [] }
-- >>> level3 = Pattern { value = "level3", elements = [level4] }
-- >>> level2 = Pattern { value = "level2", elements = [level3] }
-- >>> level1 = Pattern { value = "level1", elements = [level2] }
-- >>> pattern = Pattern { value = "root", elements = [level1] }
-- >>> size pattern
-- 5
--
-- Pattern with varying branch depths:
--
-- >>> branch1Leaf = Pattern { value = "b1leaf", elements = [] }
-- >>> branch1 = Pattern { value = "b1", elements = [branch1Leaf] }
-- >>> branch2Mid = Pattern { value = "b2mid", elements = [] }
-- >>> branch2Leaf = Pattern { value = "b2leaf", elements = [] }
-- >>> branch2 = Pattern { value = "b2", elements = [branch2Mid, branch2Leaf] }
-- >>> branch3 = Pattern { value = "b3", elements = [] }
-- >>> pattern = Pattern { value = "root", elements = [branch1, branch2, branch3] }
-- >>> size pattern
-- 7
--
-- === Edge Cases
--
-- **Atomic patterns** (no elements):
--
-- >>> size (Pattern { value = "atom", elements = [] })
-- 1
--
-- **Patterns with empty elements list**:
--
-- >>> size (Pattern { value = "empty", elements = [] })
-- 1
--
-- **Patterns with many direct elements**:
--
-- >>> elems = map (\i -> Pattern { value = i, elements = [] }) [1..10]
-- >>> pattern = Pattern { value = 100, elements = elems }
-- >>> size pattern
-- 11
--
-- **Deep nesting** (many levels):
--
-- >>> level5 = Pattern { value = 1, elements = [] }
-- >>> level4 = Pattern { value = 2, elements = [level5] }
-- >>> level3 = Pattern { value = 3, elements = [level4] }
-- >>> level2 = Pattern { value = 4, elements = [level3] }
-- >>> level1 = Pattern { value = 5, elements = [level2] }
-- >>> pattern = Pattern { value = 6, elements = [level1] }
-- >>> size pattern
-- 6
--
-- === Performance
--
-- The @size@ function traverses the entire pattern structure recursively,
-- visiting every node exactly once. Time complexity is O(n) where n is the
-- total number of nodes in the pattern structure. For patterns with up to
-- 1000 nodes, the function should complete in under 10 milliseconds.
--
-- === Type Safety
--
-- The @size@ function works with patterns of any value type @v@:
--
-- >>> size (Pattern { value = "test", elements = [] } :: Pattern String)
-- 1
-- >>> size (Pattern { value = 42, elements = [] } :: Pattern Int)
-- 1
--
size :: Pattern v -> Int
size (Pattern _ els) = 1 + sum (map size els)

-- | Query the maximum nesting depth of a pattern structure.
--
-- Returns the maximum depth of any path from the root to a leaf node in the
-- pattern structure. This provides insight into pattern complexity and helps
-- validate depth constraints.
--
-- The @depth@ function measures the maximum nesting level:
--
-- * Atomic patterns (no elements) have depth 0 (root only, no nesting)
-- * Patterns with elements have depth 1 + the maximum depth of any element
-- * The depth is the maximum across all branches in the pattern structure
--
-- This is different from @size@, which counts total nodes, and @length@,
-- which counts only direct children. The @depth@ function provides the
-- maximum path length from root to any leaf.
--
-- === Depth Counting Convention
--
-- Depth follows standard tree depth conventions:
--
-- * Depth 0: Atomic pattern (root only, no nesting levels below root)
-- * Depth 1: One level of nesting (root -> element)
-- * Depth n: n levels of nesting (root -> ... -> leaf, n steps)
--
-- === Recursive Definition
--
-- The @depth@ function is defined recursively:
--
-- @
-- depth (Pattern _ []) = 0
-- depth (Pattern _ els) = 1 + maximum (map depth els)
-- @
--
-- This means:
-- * Atomic patterns (no elements) have depth 0
-- * Patterns with elements have depth 1 plus the maximum depth of any element
-- * The maximum is taken across all branches to find the deepest path
--
-- === Examples
--
-- Atomic pattern (no nesting):
--
-- >>> atom = Pattern { value = "atom", elements = [] }
-- >>> depth atom
-- 0
--
-- One level of nesting:
--
-- >>> elem = Pattern { value = "elem", elements = [] }
-- >>> pattern = Pattern { value = "pattern", elements = [elem] }
-- >>> depth pattern
-- 1
--
-- Multiple branches with different depths:
--
-- >>> branch1Leaf = Pattern { value = "b1leaf", elements = [] }
-- >>> branch1 = Pattern { value = "b1", elements = [branch1Leaf] }
-- >>> branch2Mid = Pattern { value = "b2mid", elements = [] }
-- >>> branch2Leaf = Pattern { value = "b2leaf", elements = [] }
-- >>> branch2Inner = Pattern { value = "b2inner", elements = [branch2Leaf] }
-- >>> branch2 = Pattern { value = "b2", elements = [branch2Mid, branch2Inner] }
-- >>> branch3 = Pattern { value = "b3", elements = [] }
-- >>> pattern = Pattern { value = "root", elements = [branch1, branch2, branch3] }
-- >>> depth pattern
-- 3
--
-- Deeply nested pattern:
--
-- >>> level4 = Pattern { value = "level4", elements = [] }
-- >>> level3 = Pattern { value = "level3", elements = [level4] }
-- >>> level2 = Pattern { value = "level2", elements = [level3] }
-- >>> level1 = Pattern { value = "level1", elements = [level2] }
-- >>> pattern = Pattern { value = "root", elements = [level1] }
-- >>> depth pattern
-- 4
--
-- === Edge Cases
--
-- **Atomic patterns** (no elements):
--
-- >>> depth (Pattern { value = "atom", elements = [] })
-- 0
--
-- **Patterns with empty elements list**:
--
-- >>> depth (Pattern { value = "empty", elements = [] })
-- 0
--
-- **Patterns with many direct elements** (all atomic):
--
-- >>> elems = map (\i -> Pattern { value = i, elements = [] }) [1..10]
-- >>> pattern = Pattern { value = 100, elements = elems }
-- >>> depth pattern
-- 1
--
-- **Deep nesting** (linear chain):
--
-- >>> level5 = Pattern { value = 1, elements = [] }
-- >>> level4 = Pattern { value = 2, elements = [level5] }
-- >>> level3 = Pattern { value = 3, elements = [level4] }
-- >>> level2 = Pattern { value = 4, elements = [level3] }
-- >>> level1 = Pattern { value = 5, elements = [level2] }
-- >>> pattern = Pattern { value = 6, elements = [level1] }
-- >>> depth pattern
-- 5
--
-- === Relationship to size
--
-- The @depth@ function is always less than or equal to @size - 1@:
--
-- @
-- depth p <= size p - 1
-- @
--
-- This is because the worst-case depth occurs in a linear chain where
-- depth = size - 1. In other structures, depth is typically less.
--
-- === Performance
--
-- The @depth@ function traverses the entire pattern structure recursively,
-- visiting every node to find the maximum depth. Time complexity is O(n)
-- where n is the total number of nodes. For patterns with up to 100 levels
-- of nesting, the function should complete in under 5 milliseconds.
--
-- === Type Safety
--
-- The @depth@ function works with patterns of any value type @v@:
--
-- >>> depth (Pattern { value = "test", elements = [] } :: Pattern String)
-- 0
-- >>> depth (Pattern { value = 42, elements = [] } :: Pattern Int)
-- 0
--
depth :: Pattern v -> Int
depth (Pattern _ els) = case els of
  [] -> 0
  _  -> 1 + maximum (map depth els)

-- | Extract all values from a pattern structure as a flat list.
--
-- Returns all values from the pattern structure, including the pattern's own
-- value and all element values at all nesting levels, as a single flat list.
-- This enables value aggregation, analysis, and transformation operations.
--
-- The @values@ function extracts all values in a specific order:
--
-- * The pattern's own value appears first in the result
-- * Element values are included recursively in order
-- * Values from all nesting levels are included
-- * The result is always a flat list (no nested lists)
--
-- This function is equivalent to @toList@ from the Foldable instance and
-- @flatten@ function. It provides an explicit, intentional way to extract
-- all values from a pattern structure.
--
-- === Relationship to toList and flatten
--
-- The @values@ function is equivalent to both @toList@ and @flatten@:
--
-- @
-- values p = toList p
-- values p = flatten p
-- @
--
-- All three functions extract all values as a flat list. Use @values@ when
-- you want to make value extraction explicit, or use @toList@ for standard
-- Foldable behavior, or @flatten@ for explicit flattening operations.
--
-- === Relationship to size
--
-- The number of values returned equals the total number of nodes:
--
-- @
-- length (values p) == size p
-- @
--
-- This is because each node in the pattern structure contributes exactly
-- one value to the result.
--
-- === Relationship to value
--
-- The first value in the result is always the pattern's own value:
--
-- @
-- head (values p) == value p
-- @
--
-- This ensures that the pattern's decoration value is always accessible
-- as the first element of the values list.
--
-- === Examples
--
-- Atomic pattern:
--
-- >>> atom = Pattern { value = "atom", elements = [] }
-- >>> values atom
-- ["atom"]
--
-- Pattern with multiple elements:
--
-- >>> elem1 = Pattern { value = "e1", elements = [] }
-- >>> elem2 = Pattern { value = "e2", elements = [] }
-- >>> elem3 = Pattern { value = "e3", elements = [] }
-- >>> pattern = Pattern { value = "root", elements = [elem1, elem2, elem3] }
-- >>> values pattern
-- ["root", "e1", "e2", "e3"]
--
-- Nested pattern structure:
--
-- >>> inner = Pattern { value = "inner", elements = [] }
-- >>> middle = Pattern { value = "middle", elements = [inner] }
-- >>> outer = Pattern { value = "outer", elements = [middle] }
-- >>> pattern = Pattern { value = "root", elements = [outer] }
-- >>> values pattern
-- ["root", "outer", "middle", "inner"]
--
-- Pattern with varying nesting depths:
--
-- >>> branch1Leaf = Pattern { value = "b1leaf", elements = [] }
-- >>> branch1 = Pattern { value = "b1", elements = [branch1Leaf] }
-- >>> branch2Mid = Pattern { value = "b2mid", elements = [] }
-- >>> branch2Leaf = Pattern { value = "b2leaf", elements = [] }
-- >>> branch2 = Pattern { value = "b2", elements = [branch2Mid, branch2Leaf] }
-- >>> branch3 = Pattern { value = "b3", elements = [] }
-- >>> pattern = Pattern { value = "root", elements = [branch1, branch2, branch3] }
-- >>> values pattern
-- ["root", "b1", "b1leaf", "b2", "b2mid", "b2leaf", "b3"]
--
-- Using values for aggregation:
--
-- >>> pattern = Pattern { value = 10, elements = [Pattern { value = 5, elements = [] }, Pattern { value = 3, elements = [] }] }
-- >>> sum (values pattern)
-- 18
--
-- === Edge Cases
--
-- **Atomic patterns** (no elements):
--
-- >>> values (Pattern { value = "atom", elements = [] })
-- ["atom"]
--
-- **Patterns with empty elements list**:
--
-- >>> values (Pattern { value = "empty", elements = [] })
-- ["empty"]
--
-- **Patterns with many direct elements**:
--
-- >>> elems = map (\i -> Pattern { value = i, elements = [] }) [1..5]
-- >>> pattern = Pattern { value = 100, elements = elems }
-- >>> values pattern
-- [100, 1, 2, 3, 4, 5]
--
-- **Deep nesting** (many levels):
--
-- >>> level4 = Pattern { value = 1, elements = [] }
-- >>> level3 = Pattern { value = 2, elements = [level4] }
-- >>> level2 = Pattern { value = 3, elements = [level3] }
-- >>> level1 = Pattern { value = 4, elements = [level2] }
-- >>> pattern = Pattern { value = 5, elements = [level1] }
-- >>> values pattern
-- [5, 4, 3, 2, 1]
--
-- === Performance
--
-- The @values@ function traverses the entire pattern structure recursively,
-- visiting every node exactly once. Time complexity is O(n) where n is the
-- total number of nodes. For patterns with up to 1000 nodes, the function
-- should complete in under 10 milliseconds.
--
-- === Type Safety
--
-- The @values@ function works with patterns of any value type @v@:
--
-- >>> values (Pattern { value = "test", elements = [] } :: Pattern String)
-- ["test"]
-- >>> values (Pattern { value = 42, elements = [] } :: Pattern Int)
-- [42]
--
values :: Pattern v -> [v]
values = toList
